Add files via upload

diff --git a/src/share/restore-yalpack b/src/share/restore-yalpack
--- a/src/share/restore-yalpack
+++ b/src/share/restore-yalpack
@@ -26,21 +26,60 @@
 # restore a missing (or partially-missing) directory tree at /var/yalpack.
 # The default PKGTREES directory can also be used.
 
-HEAD=/var/yalpack
-PKGDATA=$HEAD/pkgdata
-STAGING=$HEAD/packages
-PKGTREES=$PKGDATA/TREES
-OLDTREES=$PKGDATA/TREES-OLD
-PKGVERS=$PKGDATA/VER
-SYMTREES=$PKGDATA/SYMTREES
-SYMDESTS=$PKGDATA/.SYMDESTS
-BINDEPS=$HEAD/BIN-DEPS
-NEWFILES=$PKGDATA/NEWFILES
+unset HEAD
+unset VARBKUP
+unset ROOTHOME
+unset TMP
+unset SBINDIR
+
+CHOME=/etc/yalpack.conf
+HEAD="$(grep -m 1 HEAD\= "$CHOME" | cut -d'=' -f2-)"
+VARBKUP="$(grep -m 1 VARBKUP\= "$CHOME" | cut -d'=' -f2-)"
+ROOTHOME="$(grep -m 1 ROOTHOME\= "$CHOME" | cut -d'=' -f2-)"
+TMP="$(grep -m 1 TMP\= "$CHOME" | cut -d'=' -f2-)"
+SBINDIR="$(grep -m 1 SBINDIR\= "$CHOME" | cut -d'=' -f2-)"
+
+if [ ! -f "$CHOME" ]; then
+        echo
+        echo Warning! $(tput smul)"$CHOME"$(tput rmul) was not found!
+        echo The document can be found in its originally-installed state at
+        echo $(tput smul)/usr/share/doc/yalpack-0.1.8/yalpack.conf.backup.$(tput rmul)
+        echo
+        echo Exiting now
+        echo
+        exit 1
+fi
+
+COUNT1=0
+for v in "$HEAD" "$VARBKUP" "$ROOTHOME" "$TMP" "$SBINDIR"; do
+        COUNT1=$((COUNT1 + 1))
+        COUNT2=0
+        [ -z "$v" ] && echo && echo '   'One or more variables in $(tput smul)"$CHOME"$(tput rmul) is missing, contains a space, or is not && echo '   'an absolute file path. Exiting now. && echo && exit 1
+        [ -n "$(echo "$v" | grep ' ')" ] && echo && echo '      'One or more variables in $(tput smul)"$CHOME"$(tput rmul) is missing, contains a space, or is not && echo '      'an absolute file path. Exiting now. && echo && exit 1
+        [ "$(echo "$v" | cut -c1)" != "/" ] && echo && echo '   'One or more variables in $(tput smul)"$CHOME"$(tput rmul) is missing, contains a space, or is not && echo '      'an absolute file path. Exiting now. && echo && exit 1
+        for y in "$HEAD" "$VARBKUP" "$ROOTHOME" "$TMP" "$SBINDIR"; do
+                COUNT2=$((COUNT2 + 1))
+                if [ "$v" = "$y" ] && [ "$COUNT1" != "$COUNT2" ]; then
+                        echo '  '$(tput smul)Warning!$(tput rmul) Two of the current variables have the same value.
+                        echo '  'Exiting now. Please edit $(tput smul)"$CHOME"$(tput rmul).
+                        echo
+                        exit 1
+                fi
+        done
+done
+
+PKGDATA="$HEAD"/pkgdata
+STAGING="$HEAD"/packages
+PKGTREES="$PKGDATA"/TREES
+OLDTREES="$PKGDATA"/TREES-OLD
+PKGVERS="$PKGDATA"/VER
+SYMTREES="$PKGDATA"/SYMTREES
+SYMDESTS="$PKGDATA"/.SYMDESTS
+BINDEPS="$HEAD"/BIN-DEPS
+NEWFILES="$PKGDATA"/NEWFILES
 
 # Backups
 
-VARBKUP=/var/log/yalpack
-ROOTHOME=/root
 ROOTBKUP="$ROOTHOME"/.yalpack-backup
 
 echo
@@ -111,32 +150,45 @@ if [ "$TREESOURCE" != "$PKGTREES" ]; then
 	fi
 	[ -d "$PKGTREES" ] && echo '	'Moving the current $(tput smul)"$PKGTREES"$(tput rmul) directory to $(tput smul)"$OLDTREES"$(tput rmul). && rm -rf "$OLDTREES"  && mv "$PKGTREES" "$OLDTREES" && echo
 	cp -rv "$TREESOURCE" "$PKGTREES"
+	# Directories inside PKGTREES can cause problems; fixing now.
+	[ -n "$(find "$PKGTREES"/* -type d)" ] && echo && echo '	'A directory has been found inside $(tput smul)"$PKGTREES"$(tput rmul). Please ensure that only && echo '	'files exist inside "$PKGTREES" and run the script again.
 	echo
 fi
-
-# Restoring library information with liblist -n
-echo '	'Now using $(tput smul)liblist$(tput rmul) to restore library information.
-echo
-liblist -n > /dev/null 2>&1
-echo '	'Done running $(tput smul)liblist$(tput rmul). $(tput smul)"$BINDEPS"$(tput rmul) has been restored.
-echo
 
 # Restoring other package information with pkgcheck
 echo '	'Now using $(tput smul)pkgcheck$(tput rmul) to restore ancillary package information. This may take
 echo '	'some time.
 echo
-find "$PKGTREES"/* -type f | while read -r f; do
-	g="$(basename "$f")"
-	echo '	'"$g"
-	pkgcheck "$g" > /dev/null 2>&1
+# Passing the variables.
+find "$PKGTREES"/* -type f | while read -r pkg; do
+package="$(basename "$pkg")"
+echo '		'"$package"
+YALCONFIG=yes \
+HEAD="$HEAD" \
+VARBKUP="$VARBKUP" \
+ROOTHOME="$ROOTHOME" \
+TMP="$TMP" \
+SBINDIR="$SBINDIR" "$SBINDIR"/pkgcheck "$package" > /dev/null 2>&1
 done
+
 echo
 echo '	'Thank you for your patience. Done with checking packages.
 echo
 
+# Restoring library information with liblist -n
+echo '	'Now using $(tput smul)liblist$(tput rmul) to restore library information.
+echo
+YALCONFIG=yes \
+HEAD="$HEAD" \
+VARBKUP="$VARBKUP" \
+ROOTHOME="$ROOTHOME" \
+TMP="$TMP" \
+SBINDIR="$SBINDIR" "$SBINDIR"/liblist -n > /dev/null 2>&1
+echo '	'Done running $(tput smul)liblist$(tput rmul). $(tput smul)"$BINDEPS"$(tput rmul) has been restored.
+echo
+
 # Restoring SYMTREES, if any
-echo '	'Now restoring or replacing the $(tput smul)SYMTREES$(tput rmul) directory. Although most packages
-echo '	'will not have SYMTREE files, this may take some time.
+echo '	'Now restoring or replacing the $(tput smul)SYMTREES$(tput rmul) directory.
 echo
 rm -rf "$SYMTREES" "$SYMDESTS"
 mkdir -p "$SYMTREES" "$SYMDESTS"
@@ -144,24 +196,59 @@ mkdir -p "$SYMTREES" "$SYMDESTS"
 touch "$SYMTREES"/PLACEHOLDER
 touch "$SYMDESTS"/PLACEHOLDER
 find "$PKGTREES"/* -type f | while read -r f; do
+	rm -f "$PKGDATA"/SYMTEMP
+	rm -f "$PKGDATA"/SYMTEMP2
         tree="$(basename "$f")"
-        # Checking for files installed under symlinked paths and documenting the non-symlinked
-        # file path.
+        # Checking for files installed under symlinked paths and documenting the
+	# non-symlinked file path.
         while read -r line; do
-	if [ -f "$line" ] || [ -h "$line" ] || [ -d "$line" ]; then
-                unset LINK
-                LINK="$(readlink -e "$line")" || true
-               	# Trying to avoid doubles
-             	if [ -n "$LINK" ] && \
-              	[ "$LINK" != "$line" ] && \
-              	[ -z "$(grep -x "$LINK" "$f")" ] && \
-        	[ -z "$(grep -x "$LINK".new "$f")" ]; then
-			echo "$line" to "$LINK" >> "$SYMTREES"/"$tree"
-			echo "$LINK" >> "$SYMDESTS"/"$tree"
+		# Checking for symlinks to directories in the package tree.
+		[ -d "$line" ] && [ -h "$line" ] && echo "$line" >> "$PKGDATA"/SYMTEMP
+	done < "$f"
+	
+	# This grep will reveal those directories and all files/symlinks
+	# installed under them.
+	[ -f "$PKGDATA"/SYMTEMP ] && while read -r dir; do
+		grep ^"$dir" "$f" >> "$PKGDATA"/SYMTEMP2
+	done < "$PKGDATA"/SYMTEMP
+	
+	# If the destinations are not in PKGTREE, list in SYMTREES.
+	[ -f "$PKGDATA"/SYMTEMP2 ] && while read -r sym; do
+		unset link
+		unset linkold
+		unset linkOK
+		unset linkoldOK
+
+		symold="${sym%.new}"
+
+		link="$(readlink -e "$sym")" || true
+		linkold="$(readlink -e "$symold")" || true
+
+		[ -n "$(echo "$link")" ] && linkOK=yes
+		[ -n "$(echo "$linkold")" ] && linkoldOK=yes
+
+		unset writeOK
+		unset writeoldOK
+
+		[ "$linkOK" = yes ] && [ -z "$(grep -m 1 -x "$link" "$f")" ] && writeOK=yes
+		[ "$linkoldOK" = yes ] && [ -z "$(grep -m 1 -x "$linkold" "$f")" ] && writeoldOK=yes
+
+		if [ "$writeOK" = yes ] && [ "$writeoldOK" = yes ]; then
+	    		echo "$symold" to "$linkold" >> "$SYMTREES"/"$tree" && SYMTREEFLAG="WRITE"
+  			echo "$linkold" >> "$SYMDESTS"/"$tree"
+		elif [ "$writeoldOK" = yes ] && [ -z "$link" ]; then
+  			echo "$symold" to "$linkold" >> "$SYMTREES"/"$tree" && SYMTREEFLAG="WRITE"
+      			echo "$linkold" >> "$SYMDESTS"/"$tree"
+		elif [ "$writeOK" = yes ] && [ -z "$linkold" ]; then
+         		echo "$sym" to "$link" >> "$SYMTREES"/"$tree" && SYMTREEFLAG="WRITE"
+			echo "$link" >> "$SYMDESTS"/"$tree"
 		fi
-	fi
-done < "$f"
+	done < "$PKGDATA"/SYMTEMP2	
 done
+# In case, by some coincidence, the last package examined contained files under
+# a symlinked path.
+rm -f "$PKGDATA"/SYMTEMP
+rm -f "$PKGDATA"/SYMTEMP2
 echo '	'The $(tput smul)"$SYMTREES"$(tput rmul) directory has been repopulated.
 echo
 
@@ -190,17 +277,18 @@ find "$PKGTREES"/* -type f | while read -r f; do
 	g="$(basename "$f")"
 	unset VER
 	VER="$(cat "$PKGVERS"/"$g")"
-	[ -n "$VER" ] && echo "$g"-"$VER", list updated' '"$(date)" > "$NEWFILES"/"$g"
-	[ -z "$VER" ] && echo "$g", list updated' '"$(date)" > "$NEWFILES"/"$g"
+	rm -f "$NEWFILES"/"$g"
 	while read -r file; do
 		h="${file%.new}"
 		# Only existing .new files are written in.
-		[ "$file" != "$h" ] && [ -f "$file" ] && echo "$file" >> "$NEWFILES"/"$g"		
+		if [ "$file" != "$h" ] && [ -f "$file" ]; then
+			if [ ! -f "$NEWFILES"/"$g" ]; then
+				[ -n "$VER" ] && echo "$g"-"$VER" >> "$NEWFILES"/"$g"
+				[ -z "$VER" ] && echo "$g" >> "$NEWFILES"/"$g"
+			fi
+			echo "$file" >> "$NEWFILES"/"$g"
+		fi		
 	done < "$f"
-	# Don't keep empty NEWFILE documents.
-	unset NEWLENGTH
-	NEWLENGTH="$(wc -l "$NEWFILES"/"$g" | cut -d' ' -f1)"
-	[ "$NEWLENGTH" = "1" ] && rm -f "$NEWFILES"/"$g"
 done
 echo '	'$(tput smul)"$NEWFILES"$(tput rmul) has been regenerated.
 echo
