Staging (#2)
* Add files via upload

* Add files via upload

* Create yalpack.conf

* Add files via upload

* Add files via upload

* Add files via upload

* Add files via upload

* Add files via upload

* Add files via upload

* Update README

* Delete pkgfind

* Update README.md

* Update README

* Update libcheck

* Update libprecise

* Update pkglist

* Update yalfind

* Update install.sh

* Update liblist

* Update pkgcheck

* Update pkginst

* Update pkgmake

* Update pkgremove

* Update pkgup

* Update backups

* Update newfiles

* Update restore-yalpack

diff --git a/src/bin/pkglist b/src/bin/pkglist
--- a/src/bin/pkglist
+++ b/src/bin/pkglist
@@ -1,6 +1,7 @@
 #!/bin/sh
 #
-# pkglist: lists packages (made by pkgmake and installed by pkginst) for LFS systems
+# pkglist: lists packages (made by pkgmake and installed by pkginst) for LFS
+# systems
 #
 # Copyright 2021 K. Eugene Carlson  Tsukuba, Japan
 # All rights reserved.
@@ -24,35 +25,68 @@
 #
 # Providing a list of installed packages with versioning information
 
-HEAD=/var/yalpack
-PKGDATA=$HEAD/pkgdata
-VERS=$PKGDATA/VER
-TREES=$PKGDATA/TREES
+unset HEAD
+unset VARBKUP
+unset ROOTHOME
+unset TMP
+unset SBINDIR
+
+CHOME=/etc/yalpack.conf
+HEAD="$(grep -m 1 HEAD\= "$CHOME" | cut -d'=' -f2-)"
+VARBKUP="$(grep -m 1 VARBKUP\= "$CHOME" | cut -d'=' -f2-)"
+ROOTHOME="$(grep -m 1 ROOTHOME\= "$CHOME" | cut -d'=' -f2-)"
+TMP="$(grep -m 1 TMP\= "$CHOME" | cut -d'=' -f2-)"
+SBINDIR="$(grep -m 1 SBINDIR\= "$CHOME" | cut -d'=' -f2-)"
+
+if [ ! -f "$CHOME" ]; then
+        echo
+        echo Warning! $(tput smul)"$CHOME"$(tput rmul) was not found!
+        echo The document can be found in its default state at
+        echo $(tput smul)/usr/share/doc/yalpack-0.1.8/yalpack.conf.backup.$(tput rmul)
+        echo
+        echo Exiting now
+        echo
+        exit 1
+fi
+
+COUNT1=0
+for v in "$HEAD" "$VARBKUP" "$ROOTHOME" "$TMP" "$SBINDIR"; do
+        COUNT1=$((COUNT1 + 1))
+        COUNT2=0
+        [ -z "$v" ] && echo && echo '   'One or more variables in $(tput smul)"$CHOME"$(tput rmul) is missing, contains a space, or is not && echo '   'an absolute file path. Exiting now. && echo && exit 1
+        [ -n "$(echo "$v" | grep ' ')" ] && echo && echo '      'One or more variables in $(tput smul)"$CHOME"$(tput rmul) is missing, contains a space, or is not && echo '	'an absolute file path. Exiting now. && echo && exit 1
+	[ "$(echo "$v" | cut -c1)" != "/" ] && echo && echo '	'One or more variables in $(tput smul)"$CHOME"$(tput rmul) is missing, contains a space, or is not && echo '	'an absolute file path. Exiting now. && echo && exit 1
+	for y in "$HEAD" "$VARBKUP" "$ROOTHOME" "$TMP" "$SBINDIR"; do
+                COUNT2=$((COUNT2 + 1))
+                if [ "$v" = "$y" ] && [ "$COUNT1" != "$COUNT2" ]; then
+                        echo '  '$(tput smul)Warning!$(tput rmul) Two of the current variables have the same value.
+                        echo '  'Exiting now. Please edit $(tput smul)"$CHOME"$(tput rmul).
+                        echo
+                        exit 1
+                fi
+        done
+done
+
+PKGDATA="$HEAD"/pkgdata
+VERS="$PKGDATA"/VER
+TREES="$PKGDATA"/TREES
 
 full() {
-find $TREES/* -maxdepth 0 | while read -r file;
+find "$TREES"/* -maxdepth 0 | while read -r file;
 do
-	g="$(basename "$file")"
-	if [ -n "$g" ]; then
-		if [ -n "$(cat $VERS/"$g")" ]; then
-			[ -n "$1" ] && echo "$g"-"$(cat $VERS/"$g")" | grep "$1"
-			[ -z "$1" ] && echo "$g"-"$(cat $VERS/"$g")"
-		else
-			[ -n "$1" ] && echo "$g" | grep "$1"
-			[ -z "$1" ] && echo "$g"
-		fi
-	fi
+	[ -n "$1" ] && head -n 1 "$file" | grep "$1"
+	[ -z "$1" ] && head -n 1 "$file"
 done
 echo
 }
 
 nameonly() {
-find $TREES/* -maxdepth 0 | while read -r file;
+find "$TREES"/* -maxdepth 0 | while read -r file;
 do
 	g="$(basename "$file")"
 	if [ -n "$g" ]; then
-		[ -z "$1" ] && echo "$g"
 		[ -n "$1" ] && echo "$g" | grep "$1"
+		[ -z "$1" ] && echo "$g"
 	fi
 done
 echo
diff --git a/src/bin/yalfind b/src/bin/yalfind
--- a/src/bin/yalfind
+++ b/src/bin/yalfind
@@ -1,6 +1,7 @@
 #!/bin/sh
 
-# pkgfind: Use a search term or full file path to find the package providing any matching item or items.
+# yalfind: Use a search term or full file path to find the package providing any
+# matching item or items.
 #
 # Copyright 2021 K. Eugene Carlson  Tsukuba, Japan
 # All rights reserved.
@@ -24,7 +25,48 @@
 #
 # Checking for which yalpack package provided items matching a search term.
 
-HEAD=/var/yalpack
+unset HEAD
+unset VARBKUP
+unset ROOTHOME
+unset TMP
+unset SBINDIR
+
+CHOME=/etc/yalpack.conf
+HEAD="$(grep -m 1 HEAD\= "$CHOME" | cut -d'=' -f2-)"
+VARBKUP="$(grep -m 1 VARBKUP\= "$CHOME" | cut -d'=' -f2-)"
+ROOTHOME="$(grep -m 1 ROOTHOME\= "$CHOME" | cut -d'=' -f2-)"
+TMP="$(grep -m 1 TMP\= "$CHOME" | cut -d'=' -f2-)"
+SBINDIR="$(grep -m 1 SBINDIR\= "$CHOME" | cut -d'=' -f2-)"
+
+if [ ! -f "$CHOME" ]; then
+        echo
+        echo Warning! $(tput smul)"$CHOME"$(tput rmul) was not found!
+        echo The document can be found in its default state at
+        echo $(tput smul)/usr/share/doc/yalpack-0.1.8/yalpack.conf.backup.$(tput rmul)
+        echo
+        echo Exiting now
+        echo
+        exit 1
+fi
+
+COUNT1=0
+for v in "$HEAD" "$VARBKUP" "$ROOTHOME" "$TMP" "$SBINDIR"; do
+        COUNT1=$((COUNT1 + 1))
+        COUNT2=0
+        [ -z "$v" ] && echo && echo '   'One or more variables in $(tput smul)"$CHOME"$(tput rmul) is missing, contains a space, or is not && echo '   'an absolute file path. Exiting now. && echo && exit 1
+        [ -n "$(echo "$v" | grep ' ')" ] && echo && echo '      'One or more variables in $(tput smul)"$CHOME"$(tput rmul) is missing, contains a space, or is not && echo '      'an absolute file path. Exiting now. && echo && exit 1
+        [ "$(echo "$v" | cut -c1)" != "/" ] && echo && echo '   'One or more variables in $(tput smul)"$CHOME"$(tput rmul) is missing, contains a space, or is not && echo '      'an absolute file path. Exiting now. && echo && exit 1
+        for y in "$HEAD" "$VARBKUP" "$ROOTHOME" "$TMP" "$SBINDIR"; do
+                COUNT2=$((COUNT2 + 1))
+                if [ "$v" = "$y" ] && [ "$COUNT1" != "$COUNT2" ]; then
+                        echo '  '$(tput smul)Warning!$(tput rmul) Two of the current variables have the same value.
+                        echo '  'Exiting now. Please edit $(tput smul)"$CHOME"$(tput rmul).
+                        echo
+                        exit 1
+                fi
+        done
+done
+
 PKGDATA="$HEAD"/pkgdata
 TREES="$PKGDATA"/TREES
 SYMDESTS="$PKGDATA"/.SYMDESTS
@@ -104,9 +146,9 @@ echo
 for arg in "$@"; do
 case "$arg" in
 	-h|--help)
-		echo $(tput smul)pkgfind$(tput rmul): Use a search term or full file path to find the yalpack package providing it.
+		echo $(tput smul)yalfind$(tput rmul): Use a search term or full file path to find the yalpack package providing it.
 	echo
-	echo Syntax: pkgfind \(options\) SEARCHTERM1 ...
+	echo Syntax: yalfind \(options\) SEARCHTERM1 ...
 	echo
 	echo Flags:
 	echo " -f | --showfiles : Show the file names matching the search term\(s\)."
diff --git a/src/sbin/liblist b/src/sbin/liblist
--- a/src/sbin/liblist
+++ b/src/sbin/liblist
@@ -22,25 +22,69 @@
 #  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 #  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
-# Checking dynamic libraries called in by all binaries. Must be run as root or there will be no information about /sbin and /usr/sbin.
+# Checking dynamic libraries called in by all binaries. Must be run as root or 
+# there will be no information about /sbin and /usr/sbin.
 
-HEAD=/var/yalpack
-BINDEPS=$HEAD/BIN-DEPS
+# If called by another script, use the passed-in variables to save time.
+if [ "${YALCONFIG:-no}" = no ]; then
+unset HEAD
+unset VARBKUP
+unset ROOTHOME
+unset TMP
+unset SBINDIR
+
+CHOME=/etc/yalpack.conf
+HEAD="$(grep -m 1 HEAD\= "$CHOME" | cut -d'=' -f2-)"
+VARBKUP="$(grep -m 1 VARBKUP\= "$CHOME" | cut -d'=' -f2-)"
+ROOTHOME="$(grep -m 1 ROOTHOME\= "$CHOME" | cut -d'=' -f2-)"
+TMP="$(grep -m 1 TMP\= "$CHOME" | cut -d'=' -f2-)"
+SBINDIR="$(grep -m 1 SBINDIR\= "$CHOME" | cut -d'=' -f2-)"
+
+if [ ! -f "$CHOME" ]; then
+        echo
+        echo Warning! $(tput smul)"$CHOME"$(tput rmul) was not found!
+        echo The document can be found in its default state at
+        echo $(tput smul)/usr/share/doc/yalpack-0.1.8/yalpack.conf.backup.$(tput rmul)
+        echo
+        echo Exiting now
+        echo
+        exit 1
+fi
+
+COUNT1=0
+for v in "$HEAD" "$VARBKUP" "$ROOTHOME" "$TMP" "$SBINDIR"; do
+        COUNT1=$((COUNT1 + 1))
+        COUNT2=0
+        [ -z "$v" ] && echo && echo '   'One or more variables in $(tput smul)"$CHOME"$(tput rmul) is missing, contains a space, or is not && echo '   'an absolute file path. Exiting now. && echo && exit 1
+        [ -n "$(echo "$v" | grep ' ')" ] && echo && echo '      'One or more variables in $(tput smul)"$CHOME"$(tput rmul) is missing, contains a space, or is not && echo '      'an absolute file path. Exiting now. && echo && exit 1
+        [ "$(echo "$v" | cut -c1)" != "/" ] && echo && echo '   'One or more variables in $(tput smul)"$CHOME"$(tput rmul) is missing, contains a space, or is not && echo '      'an absolute file path. Exiting now. && echo && exit 1
+        for y in "$HEAD" "$VARBKUP" "$ROOTHOME" "$TMP" "$SBINDIR"; do
+                COUNT2=$((COUNT2 + 1))
+                if [ "$v" = "$y" ] && [ "$COUNT1" != "$COUNT2" ]; then
+                        echo '  '$(tput smul)Warning!$(tput rmul) Two of the current variables have the same value.
+                        echo '  'Exiting now. Please edit $(tput smul)"$CHOME"$(tput rmul).
+                        echo
+                        exit 1
+                fi
+        done
+done
+fi
+
+BINDEPS="$HEAD"/BIN-DEPS
 mkdir -p "$BINDEPS"
 
 # The function to check libraries for an individual binary
 populate() {
-BIN="$(basename "$1")"
-# An empty variable name here would be really bad
-[ -z "$BIN" ] && return
-# Not interested in library files here
-[ -n "$(echo "$BIN" | grep -e "[.]so[.]" -e "[.]so\$" -e "[.]la[.]" -e "[.]la\$" -e "[.]a[.]" -e "[.]a\$")" ] && return
-BINDIR="$BINDEPS/$BIN"
-mkdir -p "$BINDIR"
-echo "$BIN" checked "$(date)" > "$BINDIR/$BIN.libinfo"
-ldd "$1" >> "$BINDIR/$BIN.libinfo"
-# Don't need empty entries
-[ "$(wc -l "$BINDIR/$BIN.libinfo")" = "1 $BINDIR/$BIN.libinfo" ] && rm -rf "$BINDIR"
+# This line here is why yalpack should not be used with glibc-2.26 and earlier;
+# see "man 1 ldd."
+x="$(ldd "$1")"
+if [ -n "$x" ]; then
+	BIN="$(basename "$1")"
+	# An empty variable name here would be really bad
+	[ -z "$BIN" ] && return
+	BINDIR="$BINDEPS/$BIN"
+	mkdir -p "$BINDIR" && echo "$BIN" > "$BINDIR"/"$BIN".libinfo && echo "$x" >> "$BINDIR"/"$BIN".libinfo
+fi
 }
 
 # A new dynamic library usage data collection
@@ -52,7 +96,9 @@ for d in /bin /usr /sbin /opt; do
 	# Only look in if directory exists, is not a symlink and is non-empty
 	if [ -d "$d" ] && [ ! -h "$d" ] && [ -n "$(ls -A "$d")" ]; then
 		echo Checking $d
-		find $d/* -executable -type f | while read -r file; do populate "$file"; done
+		find "$d"/* -executable -type f | while read -r file; do 
+			[ -z "$(basename "$file" | grep -m 1 -e "[.]so[.]" -e "[.]so\$" -e "[.]la\$" -e "[.]a\$")" ] && populate "$file" 
+		done
 	fi
 done
 }
diff --git a/src/sbin/pkgcheck b/src/sbin/pkgcheck
--- a/src/sbin/pkgcheck
+++ b/src/sbin/pkgcheck
@@ -22,27 +22,61 @@
 #  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 #  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
-# Checking for a package's installed binaries/executables (and hence, libraries)
+# Checking for a package's installed binaries/executables (and non-executable
+# libraries)
 
-if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
-	echo
-	echo $(tput smul)pkgcheck$(tput rmul): Check for details about a yalpack package.
-	echo
-	echo Syntax: pkgcheck NAME
-	echo
-	echo Flag:
-	echo "  -h | --help : Display this help menu."
-	echo
-	exit
+# If called by another script, use the passed-in variables to save time.
+if [ "${YALCONFIG:-no}" = no ]; then
+unset HEAD
+unset VARBKUP
+unset ROOTHOME
+unset TMP
+unset SBINDIR
+
+CHOME=/etc/yalpack.conf
+HEAD="$(grep -m 1 HEAD\= "$CHOME" | cut -d'=' -f2-)"
+VARBKUP="$(grep -m 1 VARBKUP\= "$CHOME" | cut -d'=' -f2-)"
+ROOTHOME="$(grep -m 1 ROOTHOME\= "$CHOME" | cut -d'=' -f2-)"
+TMP="$(grep -m 1 TMP\= "$CHOME" | cut -d'=' -f2-)"
+SBINDIR="$(grep -m 1 SBINDIR\= "$CHOME" | cut -d'=' -f2-)"
+
+if [ ! -f "$CHOME" ]; then
+        echo
+        echo Warning! $(tput smul)"$CHOME"$(tput rmul) was not found!
+        echo The document can be found in its default state at
+        echo $(tput smul)/usr/share/doc/yalpack-0.1.8/yalpack.conf.backup.$(tput rmul)
+        echo
+        echo Exiting now
+        echo
+        exit 1
 fi
 
-HEAD=/var/yalpack
-STAGING=$HEAD/packages
-PKGDATA=$HEAD/pkgdata
-PKGTREES=$PKGDATA/TREES
-PKGTREE=$PKGTREES/"$1"
-BINDEPS=$HEAD/BIN-DEPS
-SBINDIR=/usr/sbin
+COUNT1=0
+for v in "$HEAD" "$VARBKUP" "$ROOTHOME" "$TMP" "$SBINDIR"; do
+        COUNT1=$((COUNT1 + 1))
+        COUNT2=0
+        [ -z "$v" ] && echo && echo '   'One or more variables in $(tput smul)"$CHOME"$(tput rmul) is missing, contains a space, or is not && echo '   'an absolute file path. Exiting now. && echo && exit 1
+        [ -n "$(echo "$v" | grep ' ')" ] && echo && echo '      'One or more variables in $(tput smul)"$CHOME"$(tput rmul) is missing, contains a space, or is not && echo '      'an absolute file path. Exiting now. && echo && exit 1
+        [ "$(echo "$v" | cut -c1)" != "/" ] && echo && echo '   'One or more variables in $(tput smul)"$CHOME"$(tput rmul) is missing, contains a space, or is not && echo '      'an absolute file path. Exiting now. && echo && exit 1
+        for y in "$HEAD" "$VARBKUP" "$ROOTHOME" "$TMP" "$SBINDIR"; do
+                COUNT2=$((COUNT2 + 1))
+                if [ "$v" = "$y" ] && [ "$COUNT1" != "$COUNT2" ]; then
+                        echo '  '$(tput smul)Warning!$(tput rmul) Two of the current variables have the same value.
+                        echo '  'Exiting now. Please edit $(tput smul)"$CHOME"$(tput rmul).
+                        echo
+                        exit 1
+                fi
+        done
+done
+fi
+
+STAGING="$HEAD"/packages
+PKGDATA="$HEAD"/pkgdata
+PKGTREES="$PKGDATA"/TREES
+BINDEPS="$HEAD"/BIN-DEPS
+
+main () {
+PKGTREE="$PKGTREES"/"$1"
 
 [ "${CHECK:-yes}" = yes ] && echo
 echo '	'Preparing to check for information about $(tput smul)"$1"$(tput rmul).
@@ -55,9 +89,9 @@ unset NAME
 [ ! -f "$PKGTREE" ] && echo '	'$(tput smul)Warning!$(tput rmul) Package not found. Exiting now. && exit
 NAME=$(basename "$PKGTREE")
 
-PKGBIN=$PKGDATA/PKG-BINS/"$NAME"
-PKGDEP=$PKGDATA/PKG-DEPS/"$NAME"
-PKGLIB=$PKGDATA/PKG-LIBS/"$NAME"
+PKGBIN="$PKGDATA"/PKG-BINS/"$NAME"
+PKGDEP="$PKGDATA"/PKG-DEPS/"$NAME"
+PKGLIB="$PKGDATA"/PKG-LIBS/"$NAME"
 
 mkdir -p "$BINDEPS"
 mkdir -p "$PKGBIN"
@@ -70,35 +104,38 @@ mkdir -p "$PKGLIB"
 [ -f "$PKGLIB/libs" ] && mv "$PKGLIB"/libs "$PKGLIB"/.libs.old
 echo '	'Backed up data lists.
 echo
+
+rm -f "$PKGBIN"/real-instbins
+
 # Looking for executables, divided between libraries and others (symlinks also)
-while read -r f; do
-	h="${f%.new}"
-	file="$f"
-	unset NEWFILE
-	[ "$h" != "$file" ] && NEWFILE=yes
-	[ "$NEWFILE" = yes ] && [ -f "$h" ] && [ ! -f "$f" ] && file="$h"
+while read -r file; do
+	# Checking for .new files (this doesn't take long).
+	h="${file%.new}"
+	# The file should not be documented as .new. (Doesn't matter in light
+	# of ldd, since binary files are not .new in principle.)
+	[ "$h" != "$file" ] && [ -f "$h" ] && file="$h"
 	if [ -x "$file" ] && [ -f "$file" ]; then
+		[ -h "$file" ] && i="$(readlink -e "$file")"
 		g="$(basename "$file")"
-		i="$(readlink -e "$file")"
 		# Non-libraries
-		if [ -z "$(echo "$g" | grep -e "[.]so[.]" -e "[.]so\$" -e "[.]la[.]" -e "[.]la\$" -e "[.]a[.]" -e "[.]a\$")" ]; then
-			# [ -x $i ] is sufficient here, because symlinks to directories fail type -f
-			if [ "$i" = "$file" ] || [ -x "$i" ] || [ ! -h "$file" ]; then
-				echo "$file" >> "$PKGBIN"/instbins
-				# liblist will return an error for files that are not dynamic binaries; the script should proceed regardless
-				set +e
+		if [ -z "$(echo "$g" | grep -e "[.]so\$" -e "[.]la\$" -e "[.]a\$" -e "[.]so[.]")" ]; then
+			# [ -x $i ] is sufficient here, because symlinks to
+			# directories fail type -f
+			if [ -x "$i" ] || [ ! -h "$file" ]; then 
+				echo "$file" >> "$PKGBIN"/instbins 
+				YALCONFIG=yes \
+				HEAD="$HEAD" \
+				VARBKUP="$VARBKUP" \
+				ROOTHOME="$ROOTHOME" \
+				TMP="$TMP" \
+				SBINDIR="$SBINDIR" \
 				"$SBINDIR"/liblist "$file" > /dev/null 2>&1
-				set -e
-				[ -f "$BINDEPS/$g/$g.libinfo" ] && cat "$BINDEPS/$g/$g.libinfo" >> "$PKGDEP"/libdeps
+				[ -f "$BINDEPS/$g/$g.libinfo" ] && cat "$BINDEPS"/"$g"/"$g".libinfo >> "$PKGDEP"/libdeps
 			fi
-		# Libraries
+		# Libraries (symlinks to libraries included).
 		else
-			echo "$f" >> "$PKGLIB/libs"
+			echo "$file" >> "$PKGLIB/libs"
 		fi
-	# The library method above is cheating; some libraries are non-executable. Completing
-	# here.
-	elif [ ! -x "$file" ] && [ -f "$file" ] && [ -n "$(echo "$file" | grep -e "[.]so[.]" -e "[.]so\$" -e "[.]la[.]" -e "[.]la\$" -e "[.]a[.]" -e "[.]a\$")" ]; then
-		echo "$file" >> "$PKGLIB/libs"
 	fi	
 done < "$PKGTREE"
 
@@ -108,15 +145,23 @@ if [ -f "$PKGBIN"/instbins ]; then
 	cat "$PKGBIN"/instbins
 	echo
 fi
+
 if [ -f "$PKGLIB"/libs ]; then
-	echo '	'These libraries were installed by $(tput smul)$"$1"$(tput rmul):
+	echo '	'These libraries were installed by $(tput smul)"$1"$(tput rmul):
 	echo
 	cat "$PKGLIB"/libs
 	echo
-	# Called with CHECK=no from pkginst and pkgup; step is skipped otherwise.
+	# Called with CHECK=no from pkginst and pkgup; step is skipped
+	# otherwise.
 	if [ "${CHECK:-yes}" != yes ]; then
 		echo '	'Now using $(tput smul)liblist -n$(tput rmul) to update all library information...
 		set +e
+		YALCONFIG=yes \
+		HEAD="$HEAD" \
+		VARBKUP="$VARBKUP" \
+		ROOTHOME="$ROOTHOME" \
+		TMP="$TMP" \
+		SBINDIR="$SBINDIR" \
 		"$SBINDIR"/liblist -n > /dev/null 2>&1
 		set -e
 		echo '	'Done.
@@ -128,7 +173,15 @@ if [ "${CHECK:-yes}" != yes ]; then
 	if [ "$NAME" = "yalpack" ] ; then
 		echo '	'This is an installation or upgrade of $(tput smul)yalpack$(tput rmul). Running $(tput smul)liblist -n$(tput rmul) now to make a
 		echo '	'collection of library information...
+		set +e
+		YALCONFIG=yes \
+		HEAD="$HEAD" \
+		VARBKUP="$VARBKUP" \
+		ROOTHOME="$ROOTHOME" \
+		TMP="$TMP" \
+		SBINDIR="$SBINDIR" \
 		"$SBINDIR"/liblist -n > /dev/null 2>&1
+		set -e
 		echo '	'Done.
 		echo
 	fi	
@@ -136,3 +189,24 @@ fi
 
 echo '	'$(tput smul)Check complete.$(tput rmul)
 echo
+}
+
+for arg in "$@"; do
+	case "$arg" in
+		-h|--help)
+		echo
+		echo $(tput smul)pkgcheck$(tput rmul): Check for details about a yalpack package.
+		echo
+		echo Syntax: pkgcheck NAME [NAME ...]
+		echo
+		echo Flag:
+		echo "  -h | --help : Display this help menu."
+		echo
+		exit
+		;;
+		*)
+		[ -n "$(find "$PKGTREES"/"$arg")" ] && main "$arg"
+		;;
+	esac
+done
+
diff --git a/src/sbin/pkginst b/src/sbin/pkginst
--- a/src/sbin/pkginst
+++ b/src/sbin/pkginst
@@ -24,35 +24,77 @@
 #
 # Installing a package from a source tarball
 
+# If called by another script, use the passed-in variables to save time.
+if [ "${YALCONFIG:-no}" = no ]; then
+
+unset HEAD
+unset VARBKUP
+unset ROOTHOME
+unset TMP
+unset SBINDIR
+
+CHOME=/etc/yalpack.conf
+HEAD="$(grep -m 1 HEAD\= "$CHOME" | cut -d'=' -f2-)"
+VARBKUP="$(grep -m 1 VARBKUP\= "$CHOME" | cut -d'=' -f2-)"
+ROOTHOME="$(grep -m 1 ROOTHOME\= "$CHOME" | cut -d'=' -f2-)"
+TMP="$(grep -m 1 TMP\= "$CHOME" | cut -d'=' -f2-)"
+SBINDIR="$(grep -m 1 SBINDIR\= "$CHOME" | cut -d'=' -f2-)"
+
+if [ ! -f "$CHOME" ]; then
+        echo
+        echo Warning! $(tput smul)"$CHOME"$(tput rmul) was not found!
+        echo The document can be found in its default state at
+        echo $(tput smul)/usr/share/doc/yalpack-0.1.8/yalpack.conf.backup.$(tput rmul)
+        echo
+        echo Exiting now
+        echo
+        exit 1
+fi
+
+COUNT1=0
+for v in "$HEAD" "$VARBKUP" "$ROOTHOME" "$TMP" "$SBINDIR"; do
+        COUNT1=$((COUNT1 + 1))
+        COUNT2=0
+        [ -z "$v" ] && echo && echo '   'One or more variables in $(tput smul)"$CHOME"$(tput rmul) is missing, contains a space, or is not && echo '   'an absolute file path. Exiting now. && echo && exit 1
+        [ -n "$(echo "$v" | grep ' ')" ] && echo && echo '      'One or more variables in $(tput smul)"$CHOME"$(tput rmul) is missing, contains a space, or is not && echo '      'an absolute file path. Exiting now. && echo && exit 1
+        [ "$(echo "$v" | cut -c1)" != "/" ] && echo && echo '   'One or more variables in $(tput smul)"$CHOME"$(tput rmul) is missing, contains a space, or is not && echo '      'an absolute file path. Exiting now. && echo && exit 1
+        for y in "$HEAD" "$VARBKUP" "$ROOTHOME" "$TMP" "$SBINDIR"; do
+                COUNT2=$((COUNT2 + 1))
+                if [ "$v" = "$y" ] && [ "$COUNT1" != "$COUNT2" ]; then
+                        echo '  '$(tput smul)Warning!$(tput rmul) Two of the current variables have the same value.
+                        echo '  'Exiting now. Please edit $(tput smul)"$CHOME"$(tput rmul).
+                        echo
+                        exit 1
+                fi
+        done
+done
+fi
+
 main (){
-HEAD=/var/yalpack
-TMP=/tmp
-STAGING=$HEAD/packages
-PKGDIR=$STAGING/"$PACK"
-PKGDATA=$HEAD/pkgdata
-BUILDDEST=$TMP/"$PACK"/dest
-PKGDEST=$PKGDIR/dest
-PKGTREES=$PKGDATA/TREES
-SYMTREES=$PKGDATA/SYMTREES
-SYMDESTS=$PKGDATA/.SYMDESTS
-PKGVER=$PKGDATA/VER
-NEWFILES=$PKGDATA/NEWFILES
-SBINDIR=/usr/sbin
+STAGING="$HEAD"/packages
+PKGDIR="$STAGING"/"$PACK"
+PKGDATA="$HEAD"/pkgdata
+PKGDEST="$PKGDIR"/dest
+PKGTREES="$PKGDATA"/TREES
+SYMTREES="$PKGDATA"/SYMTREES
+SYMDESTS="$PKGDATA"/.SYMDESTS
+PKGVER="$PKGDATA"/VER
+NEWFILES="$PKGDATA"/NEWFILES
+BUILDDEST="$TMP"/dest/"$PACK"
 
 # Backups
 
-VARBKUP=/var/log/yalpack
-# Placing yalpack data directories in locations not owned by root is not recommended.
-ROOTHOME=/root
+# Placing yalpack data directories in locations not owned by root is not
+#i recommended.
 ROOTBKUP="$ROOTHOME"/.yalpack-backup
 
 echo
 echo '	'Installing package $(tput smul)"$PACK"$(tput rmul).
 echo
 set -e
-mkdir -p $STAGING
+mkdir -p "$STAGING"
 mkdir -p "$PKGDATA" "$PKGTREES" "$PKGVER" "$NEWFILES"
-cd $STAGING
+cd "$STAGING"
 tar -xf "$PACK".tar.xz
 NAME=$(cat "$PKGDIR"/NAME)
 
@@ -60,14 +102,17 @@ NAME=$(cat "$PKGDIR"/NAME)
 [ ! -d "$PKGDEST" ] && echo '	'$(tput smul)Warning! "$PKGDEST"$(tput rmul) was not found. Exiting. && exit
 
 cd "$PKGDEST"
-# Patrick Volkerding says non-755 root is dangerous, so it can't hurt (for safety when extracting the package to root).
+# Patrick Volkerding says non-755 root is dangerous, so it can't hurt (for
+# safety when extracting the package to root).
 chmod 755 "$PKGDEST"
-# If --root-own was passed in, change ownership to root:root. Ownership is preserved at the actual install stage.
+# If --root-own was passed in, change ownership to root:root. Ownership is
+# preserved at the actual install stage.
 [ "$3" = "CHOWN" ] && chown -R root:root "$PKGDEST"
 
-# Non-directories, non-symlinks and non-binaries in etc and home will be .new; check for identical/unique. Doing nothing means .new installed. (Any other file named .new manually will be checked similarly.)
-echo "$PACK", installed' '$(date) > "$NEWFILES"/"$NAME"
-
+# Non-directories, non-symlinks and non-binaries in etc and home will be .new;
+# check for identical/unique. Doing nothing means .new installed. (Any other
+# file named .new manually will be checked similarly.)
+rm -f "$NEWFILES"/"$NAME"
 find "$PKGDEST"/ -type f | while read -r f;	
 do
 	h="${f##$PKGDEST/}"
@@ -84,9 +129,13 @@ do
 			if [ "$md5f" = "$md5i" ]; then
 				rm -f "$f"
 			else
-				# If .new file will be installed, log it and show the user afterwards.
+				# If .new file will be installed, log it and
+				# show the user afterwards.
+				[ ! -f "$NEWFILES"/"$NAME" ] && echo "$PACK" >> "$NEWFILES"/"$NAME"
 				echo "/$h" >> "$NEWFILES"/"$NAME"
-				# Change the .new file ownership and mode to match the existing file (mostly relevant for rc files)
+				# Change the .new file ownership and mode to 
+				# match the existing file (mostly relevant for 
+				# rc files)
 				chown "$(stat -c "%U:%G" "/$i")" "$f"
 				chmod "$(stat -c "%a" "/$i")" "$f"
 			fi
@@ -99,20 +148,18 @@ done
 echo '	'Done evaluating the $(tput smul).new$(tput rmul) files, if any.
 echo
 
-# Don't retain empty NEWFILE documents.
-unset NEWLENGTH
-NEWLENGTH="$(wc -l "$NEWFILES"/"$NAME" | cut -d' ' -f1)"
-[ "$NEWLENGTH" = "1" ] && rm -f "$NEWFILES"/"$NAME"
-
-# Preparing and reporting on symlinks; absolute symlinks can have been pointed at either the ultimate
-# destination or a file/directory in the build directory. Symlinks that required repair will be reported.
+# Preparing and reporting on symlinks; absolute symlinks can have been pointed 
+# at either the ultimate destination or a file/directory in the build directory.
+# Symlinks that required repair will be reported.
 while read -r f;
 do
 	if [ -h "$PKGDEST"/"$f" ]; then
 	i="${f#/}"
 	j=$(readlink "$i")
-	# If the symlink is absolute; BUILDDEST needed to test it out.
-	if [ -n "$(echo "$j" | grep "$BUILDDEST")" ]; then
+	# If the symlink is absolute; BUILDDEST needed to test it out. (Just the
+	# string; the directory itself doesn't need to exist for pkginst to
+	# work.)
+	if [ -n "$(echo "$j" | grep -m 1 "$BUILDDEST")" ]; then
 		# Pointing at BUILDDEST from time of building.
 		k="${j##$BUILDDEST}"
 		echo /"$i" "to" "$k" >> "$PKGDIR"/SYMLINKS
@@ -127,7 +174,8 @@ done < "$PKGDIR"/TREE
 # Now that changes have been made to dest, make a new tarball for extraction...
 echo '	'$(tput smul)Repackaging$(tput rmul)...
 tar -czf "$STAGING"/INPACKAGE.tar.xz ./*
-# And extract over root. (dereferencing for links; don't change directory mode or ownership)
+# And extract over root. (dereferencing for links; don't change directory mode or
+# ownership)
 cd /
 echo '	'$(tput smul)Extracting now$(tput rmul)...
 tar --dereference --hard-dereference -xf "$STAGING"/INPACKAGE.tar.xz --no-overwrite-dir
@@ -135,7 +183,8 @@ cd "$PKGDIR"
 echo '	'Done.
 echo
 
-# Running ldconfig in case of new libraries; in case of an upgrade, it should be run after removal.
+# Running ldconfig in case of new libraries; in case of an upgrade, it should be
+# run after removal.
 if [ "${UPGRADE:-no}" != yes ]; then
 	ldconfig
 	echo '	'Done running $(tput smul)ldconfig$(tput rmul).
@@ -143,7 +192,7 @@ if [ "${UPGRADE:-no}" != yes ]; then
 fi
 
 # Populate the TREE entry for future updating
-cat "$PKGDIR"/TREE > $PKGTREES/"$NAME"
+cat "$PKGDIR"/TREE > "$PKGTREES"/"$NAME"
 # Saving to the backup locations as well, if they exist. The install script for
 # yalpack will make and populate them otherwise.
 [ -d "$VARBKUP" ] && cat "$PKGDIR"/TREE > "$VARBKUP"/"$NAME"
@@ -156,24 +205,50 @@ cat "$PKGDIR"/VER > "$PKGVER"/"$NAME"
 # the install script for yalpack will make and populate it.
 unset SYMTREEFLAG
 if [ -d "$SYMTREES" ]; then
-	echo '	'Checking for installations under paths with symlinks and symlinks with
-	echo '	'destinations not provided by $(tput smul)"$PACK"$(tput rmul)...
+	rm -f "$PKGDATA"/SYMTEMP
+	rm -f "$PKGDATA"/SYMTEMP2
+	echo '	'Checking for installations under paths with symlinks.
 	while read -r line; do
-		if [ -f "$line" ] || [ -h "$line" ] || [ -d "$line" ]; then
-			unset LINK
-			# "or true" prevents pkginst from crashing if the package contains a broken symlink
-			LINK="$(readlink -e "$line")" || true
-			# Trying to avoid doubles with the original TREE document
-			if [ -n "$LINK" ] && \
-			[ "$LINK" != "$line" ] && \
-			[ -z "$(grep -x "$LINK" "$PKGTREES"/"$NAME")" ] && \
-			[ -z "$(grep -x "$LINK".new "$PKGTREES"/"$NAME")" ]; then
-				SYMTREEFLAG="WRITE"
-				echo "$line" to "$LINK" >> "$SYMTREES"/"$NAME"
-				echo "$LINK" >> "$SYMDESTS"/"$NAME"
-			fi
-		fi
+		[ -d "$line" ] && [ -h "$line" ] && echo "$line" >> "$PKGDATA"/SYMTEMP	    
 	done < "$PKGTREES"/"$NAME"
+
+	[ -f "$PKGDATA"/SYMTEMP ] && while read -r dir; do
+		grep ^"$dir" "$PKGTREES"/"$NAME" >> "$PKGDATA"/SYMTEMP2
+	done < "$PKGDATA"/SYMTEMP
+	
+	[ -f "$PKGDATA"/SYMTEMP2 ] && while read -r sym; do
+		unset link
+		unset linkold
+		unset linkOK
+		unset linkoldOK
+
+		symold="${sym%.new}"
+
+		link="$(readlink -e "$sym")" || true
+		linkold="$(readlink -e "$symold")" || true
+
+		[ -n "$(echo "$link")" ] && linkOK=yes
+		[ -n "$(echo "$linkold")" ] && linkoldOK=yes
+
+		unset writeOK
+		unset writeoldOK
+		unset SYMTREEFLAG
+
+		[ "$linkOK" = yes ] && [ -z "$(grep -m 1 -x "$link" "$PKGTREES"/"$NAME")" ] && writeOK=yes
+		[ "$linkoldOK" = yes ] && [ -z "$(grep -m 1 -x "$linkold" "$PKGTREES"/"$NAME")" ] && writeoldOK=yes
+
+		if [ "$writeOK" = yes ] && [ "$writeoldOK" = yes ]; then
+			echo "$symold" to "$linkold" >> "$SYMTREES"/"$NAME" && SYMTREEFLAG="WRITE"
+			echo "$linkold" >> "$SYMDESTS"/"$NAME"
+		elif [ "$writeoldOK" = yes ] && [ -z "$link" ]; then
+			echo "$symold" to "$linkold" >> "$SYMTREES"/"$NAME" && SYMTREEFLAG="WRITE"
+			echo "$linkold" >> "$SYMDESTS"/"$NAME"
+		elif [ "$writeOK" = yes ] && [ -z "$linkold" ]; then
+			echo "$sym" to "$link" >> "$SYMTREES"/"$NAME" && SYMTREEFLAG="WRITE"
+			echo "$link" >> "$SYMDESTS"/"$NAME"
+		fi
+	done < "$PKGDATA"/SYMTEMP2
+
 	if [ "$SYMTREEFLAG" = "WRITE" ]; then
 		echo
 		cat "$SYMTREES"/"$NAME"
@@ -181,22 +256,32 @@ if [ -d "$SYMTREES" ]; then
 	fi
 	echo '	'Done.
 	echo
+	rm -f "$PKGDATA"/SYMTEMP
+	rm -f "$PKGDATA"/SYMTEMP2
 fi
 
 # Run the install script, if any
-if [ -f "$PKGDIR/install.sh" ]; then 
+if [ -x "$PKGDIR/install.sh" ]; then 
 	echo '	'Now running $(tput smul)install.sh$(tput rmul).
 	echo
 	"$PKGDIR"/install.sh
 	echo
 fi
 
-# For the installer's edification and to update library use info
+# For the installer's edification and to update library use info.
 # pkgup handles pkgcheck for upgrades.
-[ "${UPGRADE:-no}" != yes ] && CHECK=no "$SBINDIR"/pkgcheck "$NAME"
+if [ "${UPGRADE:-no}" != yes ]; then
+	YALCONFIG=yes \
+	HEAD="$HEAD" \
+	VARBKUP="$VARBKUP" \
+	ROOTHOME="$ROOTHOME" \
+	TMP="$TMP" \
+	SBINDIR="$SBINDIR" \
+	CHECK=no "$SBINDIR"/pkgcheck "$NAME"
+fi
 
 # Inform about any repaired symlinks
-if [ -f "$PKGDIR"/SYMLINKS ]; then 
+if [ -f "$PKGDIR/SYMLINKS" ]; then 
 	echo '	'The following $(tput smul)absolute symlinks$(tput rmul) were repaired before installation:
 	echo
 	cat "$PKGDIR"/SYMLINKS
@@ -216,7 +301,8 @@ fi
 
 if [ "$SYMTREEFLAG" = "WRITE" ]; then
 	echo '	'$(tput smul)One or more installations under a symlink path have been detected.$(tput rmul)
-	# This may happen from time to time with merged-usr. Without merged-usr, it probably shouldn't.
+	# This may happen from time to time with merged-usr. Without merged-usr, it 
+	# probably shouldn't.
 	if [ ! -h "/bin" ]; then
 		echo '	'This may be a sign that the package was built incorrectly. See 
 		echo '	'$(tput smul)"$SYMTREES"/"$NAME"$(tput rmul) for a list.
diff --git a/src/sbin/pkgremove b/src/sbin/pkgremove
--- a/src/sbin/pkgremove
+++ b/src/sbin/pkgremove
@@ -1,6 +1,7 @@
 #!/bin/sh
 #
-# pkgremove: to remove packages (made by pkgmake and installed by pkginst) from LFS systems
+# pkgremove: to remove packages (made by pkgmake and installed by pkginst) from
+# LFS systems
 #
 # Copyright 2021 K. Eugene Carlson  Tsukuba, Japan
 # All rights reserved.
@@ -24,45 +25,88 @@
 #
 # Used to remove packages. HANDLE WITH CARE.
 
-main() {
-HEAD=/var/yalpack
-STAGING=$HEAD/packages
-PKGDATA=$HEAD/pkgdata
-PKGTREES=$PKGDATA/TREES
-OLDTREE=$PKGTREES/"$1"
+# If called by another script, use the passed-in variables to save time.
+if [ "${YALCONFIG:-no}" = no ]; then
+unset HEAD
+unset VARBKUP
+unset ROOTHOME
+unset TMP
+unset SBINDIR
+
+CHOME=/etc/yalpack.conf
+HEAD="$(grep -m 1 HEAD\= "$CHOME" | cut -d'=' -f2-)"
+VARBKUP="$(grep -m 1 VARBKUP\= "$CHOME" | cut -d'=' -f2-)"
+ROOTHOME="$(grep -m 1 ROOTHOME\= "$CHOME" | cut -d'=' -f2-)"
+TMP="$(grep -m 1 TMP\= "$CHOME" | cut -d'=' -f2-)"
+SBINDIR="$(grep -m 1 SBINDIR\= "$CHOME" | cut -d'=' -f2-)"
+
+if [ ! -f "$CHOME" ]; then
+        echo
+        echo Warning! $(tput smul)"$CHOME"$(tput rmul) was not found!
+        echo The document can be found in its default state at
+        echo $(tput smul)/usr/share/doc/yalpack-0.1.8/yalpack.conf.backup.$(tput rmul)
+        echo
+        echo Exiting now
+        echo
+        exit 1
+fi
+
+COUNT1=0
+for v in "$HEAD" "$VARBKUP" "$ROOTHOME" "$TMP" "$SBINDIR"; do
+        COUNT1=$((COUNT1 + 1))
+        COUNT2=0
+        [ -z "$v" ] && echo && echo '   'One or more variables in $(tput smul)"$CHOME"$(tput rmul) is missing, contains a space, or is not && echo '   'an absolute file path. Exiting now. && echo && exit 1
+        [ -n "$(echo "$v" | grep ' ')" ] && echo && echo '      'One or more variables in $(tput smul)"$CHOME"$(tput rmul) is missing, contains a space, or is not && echo '      'an absolute file path. Exiting now. && echo && exit 1
+        [ "$(echo "$v" | cut -c1)" != "/" ] && echo && echo '   'One or more variables in $(tput smul)"$CHOME"$(tput rmul) is missing, contains a space, or is not && echo '      'an absolute file path. Exiting now. && echo && exit 1
+        for y in "$HEAD" "$VARBKUP" "$ROOTHOME" "$TMP" "$SBINDIR"; do
+                COUNT2=$((COUNT2 + 1))
+                if [ "$v" = "$y" ] && [ "$COUNT1" != "$COUNT2" ]; then
+                        echo '  '$(tput smul)Warning!$(tput rmul) Two of the current variables have the same value.
+                        echo '  'Exiting now. Please edit $(tput smul)"$CHOME"$(tput rmul).
+                        echo
+                        exit 1
+                fi
+        done
+done
+fi
+
+main (){
+STAGING="$HEAD"/packages
+PKGDATA="$HEAD"/pkgdata
+PKGTREES="$PKGDATA"/TREES
+OLDTREE="$PKGTREES"/"$1"
 [ "${UPGRADE:-no}" = yes ] && OLDTREE="$PKGTREES/YALPACK-OUTGOING"
-SYMTREES=$PKGDATA/SYMTREES
-OLDSYM=$SYMTREES/"$1"
+SYMTREES="$PKGDATA"/SYMTREES
+OLDSYM="$SYMTREES"/"$1"
 [ "${UPGRADE:-no}" = yes ] && OLDSYM="$SYMTREES/YALPACK-OUTGOING"
-SYMDESTS=$PKGDATA/.SYMDESTS
-OLDSYMDEST=$SYMDESTS/"$1"
+SYMDESTS="$PKGDATA"/.SYMDESTS
+OLDSYMDEST="$SYMDESTS"/"$1"
 [ "${UPGRADE:-no}" = yes ] && OLDSYMDEST="$SYMDESTS/YALPACK-OUTGOING"
-BINS=$PKGDATA/PKG-BINS
-DEPS=$PKGDATA/PKG-DEPS
-LIBS=$PKGDATA/PKG-LIBS
-VERS=$PKGDATA/VER
-OLDVER=$VERS/"$1"
+BINS="$PKGDATA"/PKG-BINS
+DEPS="$PKGDATA"/PKG-DEPS
+LIBS="$PKGDATA"/PKG-LIBS
+VERS="$PKGDATA"/VER
+OLDVER="$VERS"/"$1"
 [ "${UPGRADE:-no}" = yes ] && OLDVER="$VERS/YALPACK-OUTGOING"
-NEWFILES=$PKGDATA/NEWFILES
-OLDNEWFILE=$NEWFILES/"$1"
+NEWFILES="$PKGDATA"/NEWFILES
+OLDNEWFILE="$NEWFILES"/"$1"
 [ "${UPGRADE:-no}" = yes ] && OLDNEWFILE="$NEWFILES/YALPACK-OUTGOING"
-RMDOC=$PKGDATA/RMDOC
-CODMR=$PKGDATA/CODMR
-RMTEMP=$PKGDATA/RMTEMP
-SAFE=$PKGDATA/SAFE
+RMDOC="$PKGDATA"/RMDOC
+CODMR="$PKGDATA"/CODMR
+RMTEMP="$PKGDATA"/RMTEMP
+SAFE="$PKGDATA"/SAFE
 
 # Backups
 
-VARBKUP=/var/log/yalpack
-VARTREE=$VARBKUP/"$1"
+VARTREE="$VARBKUP"/"$1"
 [ "${UPGRADE:-no}" = yes ] && VARTREE="$VARBKUP/YALPACK-OUTGOING"
-VARTEMP=$VARBKUP/RMTEMP
-# Putting yalpack data directories in locations not owned by root is not recommended.
-ROOTHOME=/root
-ROOTBKUP=$ROOTHOME/.yalpack-backup
-ROOTTREE=$ROOTBKUP/"$1"
+VARTEMP="$VARBKUP"/RMTEMP
+# Putting yalpack data directories in locations not owned by root is not
+# recommended.
+ROOTBKUP="$ROOTHOME"/.yalpack-backup
+ROOTTREE="$ROOTBKUP"/"$1"
 [ "${UPGRADE:-no}" = yes ] && ROOTTREE="$ROOTBKUP/YALPACK-OUTGOING"
-ROOTTEMP=$ROOTBKUP/RMTEMP
+ROOTTEMP="$ROOTBKUP"/RMTEMP
 
 if [ "$2" != "NOCONFIRM" ] && [ "${UPGRADE:-no}" != yes ]; then
 	echo
@@ -78,12 +122,11 @@ elif [ "$2" = "NOCONFIRM" ] && [ "${UPGRADE:-no}" != yes ]; then
 fi
 
 set -e
-# Although there are protections against deleting symlinks to items that are needed
-# by other packages, using pkgremove on a system with few packages could conceivably
-# cause the deletion of important symlinks. For LFS 11.0 onward, these include the
-# merged-usr symlinks. Creating the SAFE file will prevent this edge case from
-# causing potentially serious problems. (rmdir is used for handling directories, so
-# this precaution is not needed for non-symlinks)
+# Using pkgremove on a system with few packages could conceivably cause the
+# deletion of important symlinks on merged-usr systems. For LFS 11.0 onward,
+# these include the merged-usr symlinks. Creating the SAFE file will prevent
+# this edge case from causing potentially serious problems. (rmdir is used for
+# handling directories, so this precaution is not needed for non-symlinks)
 cat > "$SAFE" << "EOF"
 /bin
 /sbin
@@ -114,29 +157,26 @@ rm -f "$RMDOC" "$CODMR"
 # Producing RMDOC; it will exclude the package title and the home directory.
 while read -r line;
 do
-	[ -n "$VER" ] && [ "$line" != "$NAME"-"$VER" ] && [ "$(echo "$line" | cut -c1-5)" != "/home" ] && echo "$line" >> $RMDOC
-	[ -z "$VER" ] && [ "$line" != "$NAME" ] && [ "$(echo "$line" | cut -c1-5)" != "/home" ] && echo "$line" >> $RMDOC
+	[ -n "$VER" ] && [ "$line" != "$NAME"-"$VER" ] && [ "$(echo "$line" | cut -c1-5)" != "/home" ] && echo "$line" >> "$RMDOC"
+	[ -z "$VER" ] && [ "$line" != "$NAME" ] && [ "$(echo "$line" | cut -c1-5)" != "/home" ] && echo "$line" >> "$RMDOC"
 done < "$OLDTREE"
 mv "$OLDTREE" "$RMTEMP"/TREE
 # The backup location(s) only have TREE files.
 [ -f "$VARTREE" ] && mv "$VARTREE" "$VARTEMP"/TREE
 [ -f "$ROOTTREE" ] && mv "$ROOTTREE" "$ROOTTEMP"/TREE
 
-# Finishing RMDOC and moving the SYMTREE document, if any.
+# Moving the SYMTREE document, if any.
 if [ -f "$OLDSYMDEST" ]; then
-while read -r line;
-do
-	[ -n "$VER" ] && [ "$line" != "$NAME"-"$VER" ] && [ "$(echo "$line" | cut -c1-5)" != "/home" ] && echo "$line" >> $RMDOC
-	[ -z "$VER" ] && [ "$line" != "$NAME" ] && [ "$(echo "$line" | cut -c1-5)" != "/home" ] && echo "$line" >> $RMDOC
-done < "$OLDSYMDEST"
 mv "$OLDSYM" "$RMTEMP"/SYMTREE
 mv "$OLDSYMDEST" "$RMTEMP"/SYMDEST
 fi
 
-# Making CODMR, a line-reversed version of RMDOC. Needed for the proper handling of empty directories.
+# Making CODMR, a line-reversed version of RMDOC. Needed for the proper handling
+# of empty directories.
 tac "$RMDOC" > "$CODMR"
 
-# This is not done in case of upgrades, as these files will already belong to the new version of the package.
+# This is not done in case of upgrades, as these files will already belong to
+# the new version of the package.
 if [ "${UPGRADE:-no}" != yes ]; then
 	mkdir -p "$RMTEMP"/BIN "$RMTEMP"/DEP "$RMTEMP"/LIB
 	mv ${BINS:?}/"$NAME" "$RMTEMP"/BIN/
@@ -146,18 +186,20 @@ if [ "${UPGRADE:-no}" != yes ]; then
 	echo
 fi
 
-# Checking package for matches in other installed packages. Should be safe on a package-oriented system.
-# For files
+unset ECHOHERE
+# Checking package for matches in other installed packages. Should be safe on a 
+# package-oriented system. For files.
 while read -r line;
 do
 	if [ -f "$line" ] && [ ! -h "$line" ]; then
 		# If grep -x turns up nothing, not needed by remaining packages.
 		unset LINK
-		# Using "or true" to avoid errors when examining an already-deleted file
+		# Using "or true" to avoid errors when examining an already-
+		# deleted file
 		LINK="$(readlink -e "$line")" || true
-		if [ -z "$(grep -x "$line" "$PKGTREES"/* "$SYMDESTS"/*)" ] && \
-		[ -z "$(grep -x "$LINK" "$PKGTREES"/* "$SYMDESTS"/*)" ]; then
-			rm -fv "$line"
+		if [ -z "$(grep -m 1 -x -e "$line" -e "${line%.new}" "$PKGTREES"/* "$SYMDESTS"/*)" ] && \
+		[ -z "$(grep -m 1 -x -e "$LINK" -e "$LINK.new" -e "${LINK%.new}" "$PKGTREES"/* "$SYMDESTS"/*)" ]; then
+			rm -fv "$line" && ECHOHERE=yes
 		fi
 	fi
 done < "$RMDOC"
@@ -166,15 +208,17 @@ done < "$RMDOC"
 while read -r line;
 do
 	if [ -h "$line" ]; then
-		# Don't want to knock out symlinks to things that are still needed.
-		# Important examples for LFS 11.0 and after: /sbin, /bin
+		# Don't want to knock out symlinks to things that are still
+		# needed. Important examples for LFS 11.0 and after: /sbin,
+		# /bin
 		unset LINK
 		LINK="$(readlink -e "$line")" || true
 		# If grep -x turns up nothing, not needed by remaining packages.
-		# SAFE preserves merged-usr symlinks against low-package edge cases.
-		if [ -z "$(grep -x "$line" "$PKGTREES"/* "$SYMDESTS"/* "$SAFE")" ] && \
-		[ -z "$(grep -x "$LINK" "$PKGTREES"/* "$SYMDESTS"/*)" ]; then
-			rm -fv "$line"
+		# SAFE preserves merged-usr symlinks against low-package edge
+		# cases.
+		if [ -z "$(grep -m 1 -x "$line" "$PKGTREES"/* "$SYMDESTS"/* "$SAFE")" ] && \
+		[ -z "$(grep -m 1 -x "$LINK" "$PKGTREES"/* "$SYMDESTS"/*)" ]; then
+			rm -fv "$line" && ECHOHERE=yes
 		fi
 	fi
 done < "$RMDOC"
@@ -186,18 +230,20 @@ do
 		unset LINK
 		LINK="$(readlink -e "$line")" || true
 		# Directories are protected by rmdir, etc.
-		if [ -z "$(grep -x "$line" "$PKGTREES"/* "$SYMDESTS"/*)" ] && \
-		[ -z "$(grep -x "$LINK" "$PKGTREES"/* "$SYMDESTS"/*)" ]; then
-			# For directories (ls -A condition is to cut down on unnecessary and alarming messages)
+		if [ -z "$(grep -m 1 -x "$line" "$PKGTREES"/* "$SYMDESTS"/*)" ] && \
+		[ -z "$(grep -m 1 -x "$LINK" "$PKGTREES"/* "$SYMDESTS"/*)" ]; then
+			# For directories (ls -A condition is to cut down on
+			# unnecessary and alarming messages)
 			unset x	
-			x=$(ls -A "$line") && [ -z "$x" ] && rmdir -v --ignore-fail-on-non-empty "$line"
+			x=$(ls -A "$line") && [ -z "$x" ] && ECHOHERE=yes && rmdir -v --ignore-fail-on-non-empty "$line"
 		fi
 	fi
-# The reversed document is used here to catch directories containing only empty directories.
+# The reversed document is used here to catch directories containing only empty
+# directories.
 done < "$CODMR"
+[ "$ECHOHERE" = yes ] && echo
 
 # In case of library changes
-echo
 ldconfig
 echo '	'Done running $(tput smul)ldconfig$(tput rmul).
 echo
@@ -205,8 +251,8 @@ echo
 rm -f "$RMDOC" "$CODMR"
 rm -rf "$RMTEMP" "$VARTEMP" "$ROOTTEMP"
 rm -f "$SAFE"
-[ -n "$VER" ] && rm -fv $STAGING/"$NAME"-"$VER".tar.xz
-[ -z "$VER" ] && rm -fv $STAGING/"$NAME".tar.xz
+[ -n "$VER" ] && rm -f "$STAGING"/"$NAME"-"$VER".tar.xz
+[ -z "$VER" ] && rm -f "$STAGING"/"$NAME".tar.xz
 
 if [ "${UPGRADE:-no}" != yes ]; then
 	echo '	'The package $(tput smul)"$1"$(tput rmul) has been removed. 
diff --git a/src/share/newfiles b/src/share/newfiles
--- a/src/share/newfiles
+++ b/src/share/newfiles
@@ -25,20 +25,62 @@
 # Running this script will update the lists of .new files belonging to
 # yalpack-installed packages on the system.
 
-HEAD=/var/yalpack
-PKGDATA=$HEAD/pkgdata
-PKGTREES=$PKGDATA/TREES
-PKGVERS=$PKGDATA/VER
-NEWFILES=$PKGDATA/NEWFILES
-NEWTEMP=$PKGDATA/NEWTEMP
-KLIST=$PKGDATA/.KLIST
+unset HEAD
+unset VARBKUP
+unset ROOTHOME
+unset TMP
+unset SBINDIR
+
+CHOME=/etc/yalpack.conf
+HEAD="$(grep -m 1 HEAD\= "$CHOME" | cut -d'=' -f2-)"
+VARBKUP="$(grep -m 1 VARBKUP\= "$CHOME" | cut -d'=' -f2-)"
+ROOTHOME="$(grep -m 1 ROOTHOME\= "$CHOME" | cut -d'=' -f2-)"
+TMP="$(grep -m 1 TMP\= "$CHOME" | cut -d'=' -f2-)"
+SBINDIR="$(grep -m 1 SBINDIR\= "$CHOME" | cut -d'=' -f2-)"
+
+if [ ! -f "$CHOME" ]; then
+        echo
+        echo Warning! $(tput smul)"$CHOME"$(tput rmul) was not found!
+        echo The document can be found in its default state at
+        echo $(tput smul)/usr/share/doc/yalpack-0.1.8/yalpack.conf.backup.$(tput rmul)
+        echo
+        echo Exiting now
+        echo
+        exit 1
+fi
+
+COUNT1=0
+for v in "$HEAD" "$VARBKUP" "$ROOTHOME" "$TMP" "$SBINDIR"; do
+        COUNT1=$((COUNT1 + 1))
+        COUNT2=0
+        [ -z "$v" ] && echo && echo '   'One or more variables in $(tput smul)"$CHOME"$(tput rmul) is missing, contains a space, or is not && echo '   'an absolute file path. Exiting now. && echo && exit 1
+        [ -n "$(echo "$v" | grep ' ')" ] && echo && echo '      'One or more variables in $(tput smul)"$CHOME"$(tput rmul) is missing, contains a space, or is not && echo '      'an absolute file path. Exiting now. && echo && exit 1
+        [ "$(echo "$v" | cut -c1)" != "/" ] && echo && echo '   'One or more variables in $(tput smul)"$CHOME"$(tput rmul) is missing, contains a space, or is not && echo '      'an absolute file path. Exiting now. && echo && exit 1
+        for y in "$HEAD" "$VARBKUP" "$ROOTHOME" "$TMP" "$SBINDIR"; do
+                COUNT2=$((COUNT2 + 1))
+                if [ "$v" = "$y" ] && [ "$COUNT1" != "$COUNT2" ]; then
+                        echo '  '$(tput smul)Warning!$(tput rmul) Two of the current variables have the same value.
+                        echo '  'Exiting now. Please edit $(tput smul)"$CHOME"$(tput rmul).
+                        echo
+                        exit 1
+                fi
+        done
+done
+
+PKGDATA="$HEAD"/pkgdata
+PKGTREES="$PKGDATA"/TREES
+PKGVERS="$PKGDATA"/VER
+NEWFILES="$PKGDATA"/NEWFILES
+NEWTEMP="$PKGDATA"/NEWTEMP
+KLIST="$PKGDATA"/.KLIST
 
 picker (){
 echo
 newfile="$1"
 oldfile="${newfile%.new}"
 
-# If the old file is missing (for whatever reason), offer to move the .new file over
+# If the old file is missing (for whatever reason), offer to move the .new file
+# over
 if [ ! -f "$oldfile" ] && [ -f "$newfile" ]; then
 	echo '	'"$oldfile" was not found on the system. Enter y to move $(tput smul)"$newfile"$(tput rmul) over.
 	unset INPUT
@@ -52,7 +94,8 @@ if [ ! -f "$oldfile" ] && [ -f "$newfile" ]; then
 		echo '	'or exiting, as appropriate.
 		echo
 	fi
-	main QUIET
+	# main QUIET
+	return
 fi
 
 echo '	'"$newfile"
@@ -76,7 +119,7 @@ case "$INPUT" in
 		echo '	'Copying appears to have failed. Moving on to the next .new file
 		echo '	'or exiting, as appropriate.
 	fi
-	main QUIET
+	return
 	;;
 	b)
 	echo
@@ -86,7 +129,7 @@ case "$INPUT" in
 	else
 		echo '	'Making a backup appears to have failed. Moving on to the next
 		echo '	'.new file or exiting, as appropriate.
-		main QUIET
+		return
 	fi
 	if [ -f "$oldfile" ]; then
 		rm -f "$newfile"
@@ -95,33 +138,36 @@ case "$INPUT" in
 		echo '	'or exiting, as appropriate.
 		echo
 	fi
-	main QUIET
+	return
 	;;
 	r)
 	echo
 	rm -fv "$newfile"
-	main QUIET
+	return
 	;;
 	k)
 	echo
 	echo '	'Keeping $(tput smul)"$newfile"$(tput rmul).
-	# Bug-avoidance strategy for multiple .new files with the same basename; see "staging" comment below.
+	# Bug-avoidance strategy for multiple .new files with the same basename;
+	# see "staging" comment below.
 	unset y
 	y="$(echo "$newfile" | tr '/' '@')"
 	echo "$y" >> "$KLIST"
-	main QUIET
+	return
 	;;
 	d)
 	echo
-	# Trying to use diff on a pair of binaries would not be good. Checking first.
+	# Trying to use diff on a pair of binaries would not be good. Checking
+	# first.
 	unset x
 	unset y
 	x="$(file "$newfile" | cut -d':' -f2- | grep text)"
 	y="$(file "$oldfile" | cut -d':' -f2- | grep text)"
 	[ -z "$x" ] || [ -z "$y" ] && echo '	'One or both of these files is a $(tput smul)non-text file$(tput rmul)\; diff is not available. && main QUIET
-	# Using less is nice, but it isn't in the LFS temporary tools, so check for it
-	[ -x "/usr/bin/less" ] && diff -u "$oldfile" "$newfile" | less && main QUIET
-	diff -u "$oldfile" "$newfile" && main QUIET
+	# Using less is nice, but it isn't in the LFS temporary tools, so check 
+	# for it
+	[ -x "/usr/bin/less" ] && diff -u "$oldfile" "$newfile" | less && picker "$newfile" && return
+	diff -u "$oldfile" "$newfile" && picker "$newfile" && return
 	;;
 	x)
 	echo
@@ -144,8 +190,9 @@ mkdir -p "$NEWTEMP"
 		# Exclude the package name and date line
 		x="$(head -n 1 "$p")"
 		if [ "$n" != "$x" ]; then
-			unset y
-			# Not using the full path leads to bugs when multiple .new files have the same basename.
+			unset y                                                 
+			# Not using the full path leads to bugs when multiple 
+			# .new files have the same basename.
 			y="$(echo "$n" | tr '/' '@')"
 			echo "$n" > "$NEWTEMP"/"$y"
 		fi
@@ -173,22 +220,26 @@ rm -rf "$NEWTEMP"
 
 main (){
 echo
-rm -r "$NEWFILES"
+rm -rf "$NEWFILES"
 mkdir -p "$NEWFILES"
 find "$PKGTREES"/* -type f | while read -r f; do
 	g="$(basename "$f")"
 	VER="$(cat "$PKGVERS"/"$g")"
-	[ -n "$VER" ] && echo "$g"-"$VER", list updated' '"$(date)" > "$NEWFILES"/"$g"
-	[ -z "$VER" ] && echo "$g", list updated' '"$(date)" > "$NEWFILES"/"$g"
 	while read -r file; do
 		h="${file%.new}"
 		# Only existing .new files are written in.
-		[ "$file" != "$h" ] && [ -f "$file" ] && echo "$file" >> "$NEWFILES"/"$g"		
+		if [ "$file" != "$h" ] && [ -f "$file" ]; then
+			if [ ! -f "$NEWFILES"/"$g" ]; then
+				[ -n "$VER" ] && echo "$g"-"$VER" >> "$NEWFILES"/"$g"
+				[ -z "$VER" ] && echo "$g" >> "$NEWFILES"/"$g"
+			fi
+			echo "$file" >> "$NEWFILES"/"$g"		
+		fi
 	done < "$f"
 	# Don't keep empty NEWFILE documents.
-	unset NEWLENGTH
-	NEWLENGTH="$(wc -l "$NEWFILES"/"$g" | cut -d' ' -f1)"
-	[ "$NEWLENGTH" = "1" ] && rm -f "$NEWFILES"/"$g"
+#	unset NEWLENGTH
+#	NEWLENGTH="$(wc -l "$NEWFILES"/"$g" | cut -d' ' -f1)"
+#	[ "$NEWLENGTH" = "1" ] && rm -f "$NEWFILES"/"$g"
 done
 if [ "$1" != "QUIET" ] && [ "$1" != "NORETURN" ]; then
 	echo '	'$(tput smul)"$NEWFILES"$(tput rmul) has been updated.
