Version to 0.1.5
See the release notes.

diff --git a/src/sbin/pkgcheck b/src/sbin/pkgcheck
--- a/src/sbin/pkgcheck
+++ b/src/sbin/pkgcheck
@@ -26,7 +26,7 @@
 
 if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
 	echo
-	echo pkgcheck: Check for details about a yalpack package.
+	echo $(tput bold)pkgcheck$(tput sgr0): Check for details about a yalpack package.
 	echo
 	echo Syntax: pkgcheck NAME
 	echo
@@ -43,15 +43,15 @@ PKGTREES=$PKGDATA/TREES
 PKGTREE=$PKGTREES/"$1"
 BINDEPS=$HEAD/BIN-DEPS
 
-echo
-echo Preparing to check for information about "$1".
+[ "${CHECK:-yes}" = yes ] && echo
+echo '	'Preparing to check for information about $(tput bold)"$1"$(tput sgr0).
 echo
 set -e
 cd $STAGING
 unset NAME
 
 # Sanity check
-[ ! -f "$PKGTREE" ] && echo Warning! Package not found. Exiting now. && exit
+[ ! -f "$PKGTREE" ] && echo '	'$(tput bold)Warning!$(tput sgr0) Package not found. Exiting now. && exit
 NAME=$(basename "$PKGTREE")
 
 PKGBIN=$PKGDATA/PKG-BINS/"$NAME"
@@ -67,102 +67,71 @@ mkdir -p "$PKGLIB"
 [ -f "$PKGBIN/instbins" ] && mv "$PKGBIN"/instbins "$PKGBIN"/.instbins.old
 [ -f "$PKGDEP/libdeps" ] && mv "$PKGDEP"/libdeps "$PKGDEP"/.libdeps.old
 [ -f "$PKGLIB/libs" ] && mv "$PKGLIB"/libs "$PKGLIB"/.libs.old
-echo Backed up data lists.
+echo '	'Backed up data lists.
 echo
-# Looking for executables
+# Looking for executables, divided between libraries and others (symlinks also)
 while read -r f; do
-	if [ -x "$f" ] && [ -f "$f" ]; then
-		g="$(basename "$f")"
-		# Not interested in libraries here
-		if [ -z "$(echo "$f" | grep -e "[.]so" -e "[.]la" -e "[.]a")" ]; then
-			echo Found "$f".
-			echo "$f" >> "$PKGBIN"/instbins
-			echo Wrote "$f" to package data.
-			# liblist will return an error for files that are not dynamic binaries; the script should proceed regardless
-			set +e
-			liblist "$f" > /dev/null 2>&1
-			set -e
-			[ -f "$BINDEPS/$g/$g.libinfo" ] && cat "$BINDEPS/$g/$g.libinfo" >> "$PKGDEP"/libdeps
-			echo Used libraries written in, if any.
-			echo
-		fi
-	fi
-done < "$PKGTREE"
-# Also interested in symlinks to programs
-while read -r f; do
-	if [ -h "$f" ]; then
-		h="$(readlink "$f")"
-		if [ -z "$(echo "$h" | grep -e "[.]so" -e "[.]la" -e "[.]a")" ] && [ -x "$h" ] && [ -f "$h" ]; then
-			echo Found "$f".
-			echo "$f" >> "$PKGBIN"/instbins
-			echo Wrote "$f" to package data.
-			# liblist will return an error for files that are not dynamic binaries; the script should proceed regardless
-			set +e
-			liblist "$f" > /dev/null 2>&1
-			set -e
-			[ -f "$BINDEPS/$g/$g.libinfo" ] && cat "$BINDEPS/$g/$g.libinfo" >> "$PKGDEP"/libdeps
-			echo Used libraries written in, if any.
-			echo
-		fi
-	fi
-done < "$PKGTREE"
-
-# Adding information about anything installed to libraries.
-for z in /lib /lib64 /usr/lib /usr/libexec /usr/include
-do
-y="$(echo "$z" | wc -c)"
-y=$((y - 1))
-while read -r f
-do
-	if [ -f "$f" ] || [ -h "$f" ]; then
-		if [ "$(echo "$f" | cut -c1-"$y")" = "$z" ]; then
-			g="$(basename "$f")"
-			# Restrict to actual libraries
-			if [ -n "$(echo "$f" | grep -e "[.]so[.]" -e "[.]la[.]" -e "[.]a[.]" -e "[.]so\$" -e "[.]la\$" -e "[.]a\$")" ]; then
-				# Not interested in doubles (can happen in /usr/libexec)
-				[ ! -f "$PKGLIB/libs" ] && touch "$PKGLIB/libs"
-				[ -z "$(grep "$f" "$PKGLIB/libs")" ] && echo Found library "$f". && echo "$f" >> "$PKGLIB/libs" && echo
+	h="${f%.new}"
+	file="$f"
+	unset NEWFILE
+	[ "$h" != "$file" ] && NEWFILE=yes
+	[ "$NEWFILE" = yes ] && [ -f "$h" ] && [ ! -f "$f" ] && file="$h"
+	if [ -x "$file" ] && [ -f "$file" ]; then
+		g="$(basename "$file")"
+		i="$(readlink -e "$file")"
+		# Non-libraries
+		if [ -z "$(echo "$g" | grep -e "[.]so[.]" -e "[.]so\$" -e "[.]la[.]" -e "[.]la\$" -e "[.]a[.]" -e "[.]a\$")" ]; then
+			# [ -x $i ] is sufficient here, because symlinks to directories fail type -f
+			if [ "$i" = "$file" ] || [ -x "$i" ] || [ ! -h "$file" ]; then
+				echo "$file" >> "$PKGBIN"/instbins
+				# liblist will return an error for files that are not dynamic binaries; the script should proceed regardless
+				set +e
+				liblist "$file" > /dev/null 2>&1
+				set -e
+				[ -f "$BINDEPS/$g/$g.libinfo" ] && cat "$BINDEPS/$g/$g.libinfo" >> "$PKGDEP"/libdeps
 			fi
+		# Libraries
+		else
+			echo "$f" >> "$PKGLIB/libs"
 		fi
-	fi
+	# The library method above is cheating; some libraries are non-executable. Completing
+	# here.
+	elif [ ! -x "$file" ] && [ -f "$file" ] && [ -n "$(echo "$file" | grep -e "[.]so[.]" -e "[.]so\$" -e "[.]la[.]" -e "[.]la\$" -e "[.]a[.]" -e "[.]a\$")" ]; then
+		echo "$file" >> "$PKGLIB/libs"
+	fi	
 done < "$PKGTREE"
-done
 
 if [ -f "$PKGBIN"/instbins ]; then
-	echo These programs were installed by "$1":
+	echo '	'These programs were installed by $(tput bold)"$1"$(tput sgr0):
+	echo
 	cat "$PKGBIN"/instbins
 	echo
 fi
-if [ -f "$PKGDEP"/libdeps ]; then
-	echo The following libraries are used by "$1":
-	cat "$PKGDEP"/libdeps
-	echo
-fi
 if [ -f "$PKGLIB"/libs ]; then
-	echo Installed library information for "$1":
+	echo '	'These libraries were installed by $(tput bold)$"$1"$(tput sgr0):
+	echo
 	cat "$PKGLIB"/libs
 	echo
 	# Called with CHECK=no from pkginst and pkgup; step is skipped otherwise.
 	if [ "${CHECK:-yes}" != yes ]; then
-		echo Libraries appear to have been installed. Now using liblist -n to update all
-		echo library information. Please wait.
+		echo '	'Now using $(tput bold)liblist -n$(tput sgr0) to update all library information...
 		set +e
 		liblist -n > /dev/null 2>&1
 		set -e
-		echo Library information update done.
+		echo '	'Done.
 		echo
 	fi
 fi
 
 if [ "${CHECK:-yes}" != yes ]; then
 	if [ "$NAME" = "yalpack" ] ; then
-		echo This is an installation or upgrade of yalpack. Running liblist -n now to make a
-		echo collection of library information.
-		/sbin/liblist -n > /dev/null 2>&1
-		echo Library information for yalpack updated.
+		echo '	'This is an installation or upgrade of $(tput bold)yalpack$(tput sgr0). Running $(tput bold)liblist -n$(tput sgr0) now to make a
+		echo '	'collection of library information...
+		liblist -n > /dev/null 2>&1
+		echo '	'Done.
 		echo
 	fi	
 fi
 
-echo Check complete.
+echo '	'$(tput bold)Check complete.$(tput sgr0)
 echo
diff --git a/src/sbin/pkginst b/src/sbin/pkginst
--- a/src/sbin/pkginst
+++ b/src/sbin/pkginst
@@ -33,20 +33,30 @@ PKGDATA=$HEAD/pkgdata
 BUILDDEST=$TMP/"$PACK"/dest
 PKGDEST=$PKGDIR/dest
 PKGTREES=$PKGDATA/TREES
+SYMTREES=$PKGDATA/SYMTREES
+SYMDESTS=$PKGDATA/.SYMDESTS
 PKGVER=$PKGDATA/VER
+NEWFILES=$PKGDATA/NEWFILES
+
+# Backups
+
+VARBKUP=/var/log/yalpack
+# Placing yalpack data directories in locations not owned by root is not recommended.
+ROOTHOME=/root
+ROOTBKUP="$ROOTHOME"/.yalpack
 
 echo
-echo Installing package "$PACK".
+echo '	'Installing package $(tput bold)"$PACK"$(tput sgr0).
 echo
 set -e
 mkdir -p $STAGING
-mkdir -p "$PKGDATA" "$PKGTREES" "$PKGVER"
+mkdir -p "$PKGDATA" "$PKGTREES" "$PKGVER" "$NEWFILES"
 cd $STAGING
 tar -xf "$PACK".tar.xz
 NAME=$(cat "$PKGDIR"/NAME)
 
 # Exit code not necessary because pkgup already checks for TREE.
-[ ! -d "$PKGDEST" ] && echo Warning! "$PKGDEST" was not found. Exiting. && exit
+[ ! -d "$PKGDEST" ] && echo '	'$(tput bold)Warning! "$PKGDEST"$(tput sgr0) was not found. Exiting. && exit
 
 cd "$PKGDEST"
 # Patrick Volkerding says non-755 root is dangerous, so it can't hurt (for safety when extracting the package to root).
@@ -54,14 +64,15 @@ chmod 755 "$PKGDEST"
 # If --root-own was passed in, change ownership to root:root. Ownership is preserved at the actual install stage.
 [ "$3" = "CHOWN" ] && chown -R root:root "$PKGDEST"
 
-# Non-symlinks in etc and home will be .new; check for identical/unique. Doing nothing means .new installed. (Any other file named .new manually will be checked similarly.)
+# Non-directories, non-symlinks and non-binaries in etc and home will be .new; check for identical/unique. Doing nothing means .new installed. (Any other file named .new manually will be checked similarly.)
+echo "$PACK", installed' '$(date) > "$NEWFILES"/"$NAME"
+
 find "$PKGDEST"/ -type f | while read -r f;	
 do
 	h="${f##$PKGDEST/}"
 	i="${h%.new}"
 	# Proceed if the file is .new
 	if [ "$i" != "$h" ]; then
-		echo Checking "$f".
 		# The non-.new version will be called this, if needed
 		j="${f%.new}"
 		# If file exists, check for differences
@@ -70,95 +81,147 @@ do
 			md5i=$(md5sum "/$i" | cut -d' ' -f-1)
 			# If not different, new file is not needed
 			if [ "$md5f" = "$md5i" ]; then
-				rm -fv "$f"
-				echo
+				rm -f "$f"
 			else
 				# If .new file will be installed, log it and show the user afterwards.
-				echo "/$h" >> "$PKGDIR"/NEWFILES
+				echo "/$h" >> "$NEWFILES"/"$NAME"
 				# Change the .new file ownership and mode to match the existing file (mostly relevant for rc files)
 				chown "$(stat -c "%U:%G" "/$i")" "$f"
 				chmod "$(stat -c "%a" "/$i")" "$f"
-				echo
 			fi
 		# If file DNE, don't call the new one .new
 		else
-			echo File does not exist on this system.
-			mv -v "$f" "$j"
-			echo
+			mv "$f" "$j"
 		fi
 	fi
 done
-echo Done evaluating the .new files, if any.
+echo '	'Done evaluating the $(tput bold).new$(tput sgr0) files, if any.
 echo
+
+# Don't retain empty NEWFILE documents.
+unset NEWLENGTH
+NEWLENGTH="$(wc -l "$NEWFILES"/"$NAME" | cut -d' ' -f1)"
+[ "$NEWLENGTH" = "1" ] && rm -f "$NEWFILES"/"$NAME"
 
 # Preparing and reporting on symlinks; absolute symlinks can have been pointed at either the ultimate
-# destination or a file/directory in the build directory.
-find "$PKGDEST"/ -type l | while read -r f;
+# destination or a file/directory in the build directory. Symlinks that required repair will be reported.
+while read -r f;
 do
-	i="${f##$PKGDEST/}"
+	if [ -h "$PKGDEST"/"$f" ]; then
+	i="${f#/}"
 	j=$(readlink "$i")
 	# If the symlink is absolute; BUILDDEST needed to test it out.
-	if echo "$j" | grep -q "$BUILDDEST"; then
+	if [ -n "$(echo "$j" | grep "$BUILDDEST")" ]; then
 		# Pointing at BUILDDEST from time of building.
-		k="${j##$BUILDDEST/}"
-		echo /"$i" to /"$k" >> "$PKGDIR"/SYMLINKS
-		ln -sfv /"$k" "$f"
+		k="${j##$BUILDDEST}"
+		echo /"$i" "to" "$k" >> "$PKGDIR"/SYMLINKS
+		ln -sfn "$k" "$i"
 		echo
-	# If the symlink is relative
-	else
-		echo /"$i" to "$j" >> "$PKGDIR"/SYMLINKS
 	fi
-done
+	fi
+done < "$PKGDIR"/TREE
+
+[ -f "$PKGDIR/SYMLINKS" ] && echo '	'Symlink checks and repairs complete. && echo
 
 # Now that changes have been made to dest, make a new tarball for extraction...
+echo '	'$(tput bold)Repackaging$(tput sgr0)...
 tar -czf "$STAGING"/INPACKAGE.tar.xz ./*
-# And extract over root.
+# And extract over root. (dereferencing for links; don't change directory mode or ownership)
 cd /
-tar -xvf "$STAGING"/INPACKAGE.tar.xz --no-overwrite-dir
+echo '	'$(tput bold)Extracting now$(tput sgr0)...
+tar --dereference --hard-dereference -xf "$STAGING"/INPACKAGE.tar.xz --no-overwrite-dir
 cd "$PKGDIR"
+echo '	'Done.
 echo
 
-# Running ldconfig in case of new libraries
-echo Now running ldconfig...
-/sbin/ldconfig || true
-echo Done running ldconfig.
-echo
+# Running ldconfig in case of new libraries; in case of an upgrade, it should be run after removal.
+if [ "${UPGRADE:-no}" != yes ]; then
+	ldconfig
+	echo '	'Done running $(tput bold)ldconfig$(tput sgr0).
+	echo
+fi
 
 # Populate the TREE entry for future updating
 cat "$PKGDIR"/TREE > $PKGTREES/"$NAME"
+# Saving to the backup locations as well, if they exist. The install script for
+# yalpack will make and populate them otherwise.
+[ -d "$VARBKUP" ] && cat "$PKGDIR"/TREE > "$VARBKUP"/"$NAME"
+[ -d "$ROOTBKUP" ] && cat "$PKGDIR"/TREE > "$ROOTBKUP"/"$NAME"
 
 # Add version information to /var/yalpack/pkgdata
-mkdir -p "$PKGVER"
 cat "$PKGDIR"/VER > "$PKGVER"/"$NAME"
+
+# Make the SYMTREES document, if needed. If the directory does not yet exist,
+# the install script for yalpack will make and populate it.
+unset SYMTREEFLAG
+if [ -d "$SYMTREES" ]; then
+	echo '	'Checking for installations under paths with symlinks and symlinks with
+	echo '	'destinations not provided by $(tput bold)"$PACK"$(tput sgr0)...
+	while read -r line; do
+		if [ -f "$line" ] || [ -h "$line" ] || [ -d "$line" ]; then
+			unset LINK
+			# "or true" prevents pkginst from crashing if the package contains a broken symlink
+			LINK="$(readlink -e "$line")" || true
+			# Trying to avoid doubles with the original TREE document
+			if [ -n "$LINK" ] && \
+			[ "$LINK" != "$line" ] && \
+			[ -z "$(grep -x "$LINK" "$PKGTREES"/"$NAME")" ] && \
+			[ -z "$(grep -x "$LINK".new "$PKGTREES"/"$NAME")" ]; then
+				SYMTREEFLAG="WRITE"
+				echo "$line" to "$LINK" >> "$SYMTREES"/"$NAME"
+				echo "$LINK" >> "$SYMDESTS"/"$NAME"
+			fi
+		fi
+	done < "$PKGTREES"/"$NAME"
+	if [ "$SYMTREEFLAG" = "WRITE" ]; then
+		echo
+		cat "$SYMTREES"/"$NAME"
+		echo
+	fi
+	echo '	'Done.
+	echo
+fi
 
 # Run the install script, if any
 if [ -f "$PKGDIR/install.sh" ]; then 
-	echo Now running install.sh.
+	echo '	'Now running $(tput bold)install.sh$(tput sgr0).
+	echo
 	"$PKGDIR"/install.sh
 	echo
 fi
 
 # For the installer's edification and to update library use info
-echo
 # pkgup handles pkgcheck for upgrades.
-[ "${UPGRADE:-no}" != yes ] && CHECK=no /sbin/pkgcheck "$NAME"
+[ "${UPGRADE:-no}" != yes ] && CHECK=no pkgcheck "$NAME"
 
-# Inform about any symlinks
+# Inform about any repaired symlinks
 if [ -f "$PKGDIR"/SYMLINKS ]; then 
-	echo The following symlinks were created by the build process:
+	echo '	'The following $(tput bold)absolute symlinks$(tput sgr0) were repaired before installation:
+	echo
 	cat "$PKGDIR"/SYMLINKS
 	echo
 fi
 
 # Inform about any .new files
-if [ -f "$PKGDIR"/NEWFILES ]; then
-	echo The following .new files should be examined:
-	cat "$PKGDIR"/NEWFILES
+if [ -f "$NEWFILES/$NAME" ]; then
+	echo '	'The following $(tput bold).new$(tput sgr0) files should be examined:
 	echo
-	echo '' >> "$PKGDATA"/NEWFILE-LOG
-	echo "$PACK" installed on "$(date)" >> "$PKGDATA"/NEWFILE-LOG
-	cat "$PKGDIR"/NEWFILES >> "$PKGDATA"/NEWFILE-LOG
-	echo The list has been added to "$PKGDATA"/NEWFILE-LOG for convenience.
+	cat "$NEWFILES"/"$NAME"
+	echo
+	echo '	'The list will be stored at $(tput bold)"$NEWFILES"/"$NAME"$(tput sgr0) for reference.
+	echo '	'Run $(tput bold)/usr/share/yalpack/newfiles$(tput sgr0) to update "$NEWFILES".
+	echo
+fi
+
+if [ "$SYMTREEFLAG" = "WRITE" ]; then
+	echo '	'$(tput bold)One or more installations under a symlink path have been detected.$(tput sgr0)
+	# This may happen from time to time with merged-usr. Without merged-usr, it probably shouldn't.
+	if [ ! -h "/bin" ]; then
+		echo '	'This may be a sign tht the package was built incorrectly. See 
+		echo '	'$(tput bold)"$SYMTREES"/"$NAME"$(tput sgr0) for a list.
+	else
+		echo '	'See $(tput bold)"$SYMTREES"/"$NAME"$(tput sgr0) for a list.
+	fi
 	echo
 fi
 
@@ -167,13 +230,13 @@ cd "$STAGING"
 rm -f "$STAGING"/INPACKAGE.tar.xz
 rm -rf "${PKGDIR:?}"
 if [ "$2" != "KEEP" ]; then
-	rm -vf $STAGING/"$PACK".tar.xz
-	echo The package tarball has been removed. See $PKGTREES/"$NAME"
-	echo for a list of installed files.
+	rm -f $STAGING/"$PACK".tar.xz
+	echo '	'The package tarball has been removed. See $(tput bold)$PKGTREES/"$NAME"$(tput sgr0)
+	echo '	'for a list of installed files, symlinks and directories.
 	echo
 fi
 
-echo Installation of "$PACK" complete.
+echo '	'Installation of $(tput bold)"$PACK"$(tput sgr0) complete.
 echo
 }
 unset KEEP
@@ -184,7 +247,7 @@ for arg in "$@"; do
 	case "$arg" in
 		-h|--help)
 		echo
-		echo pkginst: Install a yalpack package from a package tarball in /var/yalpack/packages
+		echo $(tput bold)pkginst$(tput sgr0): Install a yalpack package from a package tarball in /var/yalpack/packages
 		echo
 		echo Syntax: pkginst \(options\) NAME1-VER1 NAME2-VER2 ...
 		echo 
diff --git a/src/sbin/pkgremove b/src/sbin/pkgremove
--- a/src/sbin/pkgremove
+++ b/src/sbin/pkgremove
@@ -27,34 +27,76 @@
 main() {
 HEAD=/var/yalpack
 STAGING=$HEAD/packages
-DATA=$HEAD/pkgdata
-PKGTREES=$DATA/TREES
+PKGDATA=$HEAD/pkgdata
+PKGTREES=$PKGDATA/TREES
 OLDTREE=$PKGTREES/"$1"
 [ "${UPGRADE:-no}" = yes ] && OLDTREE="$PKGTREES/YALPACK-OUTGOING"
-BINS=$DATA/PKG-BINS
-DEPS=$DATA/PKG-DEPS
-LIBS=$DATA/PKG-LIBS
-VERS=$DATA/VER
+SYMTREES=$PKGDATA/SYMTREES
+OLDSYM=$SYMTREES/"$1"
+[ "${UPGRADE:-no}" = yes ] && OLDSYM="$SYMTREES/YALPACK-OUTGOING"
+SYMDESTS=$PKGDATA/.SYMDESTS
+OLDSYMDEST=$SYMDESTS/"$1"
+[ "${UPGRADE:-no}" = yes ] && OLDSYMDEST="$SYMDESTS/YALPACK-OUTGOING"
+BINS=$PKGDATA/PKG-BINS
+DEPS=$PKGDATA/PKG-DEPS
+LIBS=$PKGDATA/PKG-LIBS
+VERS=$PKGDATA/VER
 OLDVER=$VERS/"$1"
 [ "${UPGRADE:-no}" = yes ] && OLDVER="$VERS/YALPACK-OUTGOING"
-RMDOC=$DATA/RMDOC
-RMTEMP=$DATA/RMTEMP
+NEWFILES=$PKGDATA/NEWFILES
+OLDNEWFILE=$NEWFILES/"$1"
+[ "${UPGRADE:-no}" = yes ] && OLDNEWFILE="$NEWFILES/YALPACK-OUTGOING"
+RMDOC=$PKGDATA/RMDOC
+CODMR=$PKGDATA/CODMR
+RMTEMP=$PKGDATA/RMTEMP
+SAFE=$PKGDATA/SAFE
 
-if [ "$2" != "NOCONFIRM" ]; then
+# Backups
+
+VARBKUP=/var/log/yalpack
+VARTREE=$VARBKUP/"$1"
+[ "${UPGRADE:-no}" = yes ] && VARTREE="$VARBKUP/YALPACK-OUTGOING"
+VARTEMP=$VARBKUP/RMTEMP
+# Putting yalpack data directories in locations not owned by root is not recommended.
+ROOTHOME=/root
+ROOTBKUP=$ROOTHOME/.yalpack
+ROOTTREE=$ROOTBKUP/"$1"
+[ "${UPGRADE:-no}" = yes ] && ROOTTREE="$ROOTBKUP/YALPACK-OUTGOING"
+ROOTTEMP=$ROOTBKUP/RMTEMP
+
+if [ "$2" != "NOCONFIRM" ] && [ "${UPGRADE:-no}" != yes ]; then
 	echo
-	echo It is advised to run pkgcheck on the package first.
+	echo '	'It may be a good idea to run pkgcheck on the package first.
 	echo
-	echo Removal of package "$1" has been requested. To proceed\, 
-	echo press \"y\". IF YOU HAVE ANY DOUBTS, TERMINATE THE PROCESS NOW.
+	echo '	'Removal of the package $(tput bold)"$1"$(tput sgr0) has been requested. To proceed\, 
+	echo '	'enter $(tput bold)\"y\"$(tput sgr0). If in doubt, terminate the process now.
 	read -r INPUT
 	echo
 	[ "$INPUT" != "y" ] && exit
+elif [ "$2" = "NOCONFIRM" ] && [ "${UPGRADE:-no}" != yes ]; then
+	echo
 fi
 
 set -e
-rm -rf "$RMTEMP"
+# Although there are protections against deleting symlinks to items that are needed
+# by other packages, using pkgremove on a system with few packages could conceivably
+# cause the deletion of important symlinks. For LFS 11.0 onward, these include the
+# merged-usr symlinks. Creating the SAFE file will prevent this edge case from
+# causing potentially serious problems. (rmdir is used for handling directories, so
+# this precaution is not needed for non-symlinks)
+cat > "$SAFE" << "EOF"
+/bin
+/sbin
+/lib
+/etc/mtab
+EOF
+
+rm -rf "$RMTEMP" "$VARTEMP" "$ROOTTEMP"
 mkdir -p "$RMTEMP"/VER
 mkdir -p "$RMTEMP"/NAME
+mkdir -p "$RMTEMP"/NEWFILE
+[ -d "$VARBKUP" ] && mkdir "$VARTEMP"
+[ -d "$ROOTBKUP" ] && mkdir "$ROOTTEMP"
 
 NAME="$1"
 if [ -f "$OLDVER" ]; then
@@ -62,11 +104,13 @@ if [ -f "$OLDVER" ]; then
 	mv "$OLDVER" "$RMTEMP"/VER
 fi
 
-# No exit code necessary because pkgup already checks for this.
-[ -z "$(find "$OLDTREE")" ] && echo Requested package not found. Check for the package name with pkglist. Exiting now. && exit
+[ -f "$OLDNEWFILE" ] && mv "$OLDNEWFILE" "$RMTEMP"/NEWFILE
 
-# Removing any previous RMDOC
-rm -f $RMDOC
+# No exit code necessary because pkgup already checks for this.
+[ -z "$(find "$OLDTREE")" ] && echo '	'Requested package not found. Check for the package name with $(tput bold)pkglist$(tput sgr0). Exiting now. && exit
+
+# Removing any previous RMDOC and CODMR
+rm -f "$RMDOC" "$CODMR"
 # Producing RMDOC; it will exclude the package title and the home directory.
 while read -r line;
 do
@@ -74,59 +118,103 @@ do
 	[ -z "$VER" ] && [ "$line" != "$NAME" ] && [ "$(echo "$line" | cut -c1-5)" != "/home" ] && echo "$line" >> $RMDOC
 done < "$OLDTREE"
 mv "$OLDTREE" "$RMTEMP"/TREE
+# The backup location(s) only have TREE files.
+[ -d "$VARTEMP" ] && mv "$VARTREE" "$VARTEMP"/TREE
+[ -d "$ROOTTEMP" ] && mv "$ROOTTREE" "$ROOTTEMP"/TREE
+
+# Finishing RMDOC and moving the SYMTREE document, if any.
+if [ -f "$OLDSYMDEST" ]; then
+while read -r line;
+do
+	[ -n "$VER" ] && [ "$line" != "$NAME"-"$VER" ] && [ "$(echo "$line" | cut -c1-5)" != "/home" ] && echo "$line" >> $RMDOC
+	[ -z "$VER" ] && [ "$line" != "$NAME" ] && [ "$(echo "$line" | cut -c1-5)" != "/home" ] && echo "$line" >> $RMDOC
+done < "$OLDSYMDEST"
+mv "$OLDSYM" "$RMTEMP"/SYMTREE
+mv "$OLDSYMDEST" "$RMTEMP"/SYMDEST
+fi
+
+# Making CODMR, a line-reversed version of RMDOC. Needed for the proper handling of empty directories.
+tac "$RMDOC" > "$CODMR"
 
 # This is not done in case of upgrades, as these files will already belong to the new version of the package.
 if [ "${UPGRADE:-no}" != yes ]; then
 	mkdir -p "$RMTEMP"/BIN "$RMTEMP"/DEP "$RMTEMP"/LIB
-	mv  ${BINS:?}/"$NAME" "$RMTEMP"/BIN/
+	mv ${BINS:?}/"$NAME" "$RMTEMP"/BIN/
 	mv ${DEPS:?}/"$NAME" "$RMTEMP"/DEP/
 	mv ${LIBS:?}/"$NAME" "$RMTEMP"/LIB/
-	echo Binary and library information moved to "$RMTEMP".
+	echo '	'Binary and library information moved to "$RMTEMP".
 	echo
 fi
 
 # Checking package for matches in other installed packages. Should be safe on a package-oriented system.
+# For files
 while read -r line;
 do
-	# If grep -x turns up nothing, not needed by remaining packages
-	if [ -z "$(grep -x "$line" "$PKGTREES"/*)" ]; then
-		# For files
-		[ -f "$line" ] && rm -fv "$line"
-		# For symlinks
-		[ -h "$line" ] && rm -fv "$line"
+	if [ -f "$line" ] && [ ! -h "$line" ]; then
+		# If grep -x turns up nothing, not needed by remaining packages.
+		unset LINK
+		# Using "or true" to avoid errors when examining an already-deleted file
+		LINK="$(readlink -e "$line")" || true
+		if [ -z "$(grep -x "$line" "$PKGTREES"/* "$SYMDESTS"/*)" ] && \
+		[ -z "$(grep -x "$LINK" "$PKGTREES"/* "$SYMDESTS"/*)" ]; then
+			rm -fv "$line"
+		fi
+	fi
+done < "$RMDOC"
+
+# For symlinks
+while read -r line;
+do
+	if [ -h "$line" ]; then
+		# Don't want to knock out symlinks to things that are still needed.
+		# Important examples for LFS 11.0 and after: /sbin, /bin
+		unset LINK
+		LINK="$(readlink -e "$line")" || true
+		# If grep -x turns up nothing, not needed by remaining packages.
+		# SAFE preserves merged-usr symlinks against low-package edge cases.
+		if [ -z "$(grep -x "$line" "$PKGTREES"/* "$SYMDESTS"/* "$SAFE")" ] && \
+		[ -z "$(grep -x "$LINK" "$PKGTREES"/* "$SYMDESTS"/*)" ]; then
+			rm -fv "$line"
+		fi
 	fi
 done < "$RMDOC"
 
 # Directories go afterwards to catch the empty ones properly.
 while read -r line;
 do
-	# If grep -x turns up nothing, not needed by remaining packages
-	if [ -z "$(grep -x "$line" "$PKGTREES"/*)" ]; then
-		# For directories
-		[ -d "$line" ] && x=$(ls -A "$line") && [ -z "$x" ] && rmdir -v --ignore-fail-on-non-empty "$line"
+	if [ -d "$line" ] && [ ! -h "$line" ]; then
+		unset LINK
+		LINK="$(readlink -e "$line")" || true
+		# Directories are protected by rmdir, etc.
+		if [ -z "$(grep -x "$line" "$PKGTREES"/* "$SYMDESTS"/*)" ] && \
+		[ -z "$(grep -x "$LINK" "$PKGTREES"/* "$SYMDESTS"/*)" ]; then
+			# For directories (ls -A condition is to cut down on unnecessary and alarming messages)
+			unset x	
+			x=$(ls -A "$line") && [ -z "$x" ] && rmdir -v --ignore-fail-on-non-empty "$line"
+		fi
 	fi
-done < "$RMDOC"
-
+# The reversed document is used here to catch directories containing only empty directories.
+done < "$CODMR"
 
 # In case of library changes
 echo
-echo Running ldconfig now...
-/sbin/ldconfig || true
-echo Done running ldconfig.
+ldconfig
+echo '	'Done running $(tput bold)ldconfig$(tput sgr0).
 echo
 # Cleaning up
-rm -f "$RMDOC"
-rm -rf "$RMTEMP"
+rm -f "$RMDOC" "$CODMR"
+rm -rf "$RMTEMP" "$VARTEMP" "$ROOTTEMP"
+rm -f "$SAFE"
 [ -n "$VER" ] && rm -fv $STAGING/"$NAME"-"$VER".tar.xz
 [ -z "$VER" ] && rm -fv $STAGING/"$NAME".tar.xz
 
 if [ "${UPGRADE:-no}" != yes ]; then
-	echo The package "$1" has been removed. 
-	[ "$NAME" != "yalpack" ] && echo Consider running \"liblist -n\" to update yalpack\'s dynamic library information.
+	echo '	'The package $(tput bold)"$1"$(tput sgr0) has been removed. 
+	[ "$NAME" != "yalpack" ] && echo '	'Consider running $(tput bold)\"liblist -n\"$(tput sgr0) to update dynamic library information.
 	echo
 else
-	[ -n "$VER" ] && echo Extraneous files from "$NAME"-"$VER" have been removed.
-	[ -z "$VER" ] && echo Extraneous files from "$NAME" have been removed.
+	[ -n "$VER" ] && echo '	'Any extraneous files from $(tput bold)"$NAME"-"$VER"$(tput sgr0) have been removed.
+	[ -z "$VER" ] && echo '	'Any extraneous files from $(tput bold)"$NAME"$(tput sgr0) have been removed.
 	echo
 fi
 }
@@ -136,7 +224,7 @@ for arg in "$@"; do
 	case "$arg" in
 		-h|--help)
 		echo
-		echo pkgremove: Remove a yalpack package from the system
+		echo $(tput bold)pkgremove$(tput sgr0): Remove a yalpack package from the system.
 		echo
 		echo Syntax: pkgremove \(options\) NAME1 NAME2 ...
 		echo
diff --git a/src/sbin/pkgup b/src/sbin/pkgup
--- a/src/sbin/pkgup
+++ b/src/sbin/pkgup
@@ -26,21 +26,32 @@
 
 HEAD=/var/yalpack
 STAGING=$HEAD/packages
-PKGTREES=$HEAD/pkgdata/TREES
-PKGVERS=$HEAD/pkgdata/VER
+PKGDATA=$HEAD/pkgdata
+PKGTREES=$PKGDATA/TREES
+PKGVERS=$PKGDATA/VER
+SYMTREES=$PKGDATA/SYMTREES
+SYMDESTS=$PKGDATA/.SYMDESTS
+NEWFILES=$PKGDATA/NEWFILES
+
+# Backups
+VARBKUP=/var/log/yalpack
+# Putting yalpack data directories in locations not owned by root is not recommended.
+ROOTHOME=/root
+ROOTBKUP=$ROOTHOME/.yalpack
 
 main() {
 NEWDIR=$STAGING/"$2"
 
 if [ "$4" != "NOCONFIRM" ]; then
 	echo
-	echo It is advised to run pkgcheck on the old package first.
+	echo '	'It may be a good idea to run pkgcheck on the old package first.
 	echo
-	echo Upgrade of "$1" to "$2" has been requested. To proceed, press \"y\". IF YOU HAVE ANY DOUBTS, TERMINATE THE PROCESS NOW.
+	echo '	'An upgrade of $(tput bold)"$1"$(tput sgr0) to $(tput bold)"$2"$(tput sgr0) has been requested. To proceed,
+	echo '	'enter $(tput bold)\"y\"$(tput sgr0). If in doubt, terminate the process now.
 	read -r INPUT
 	[ "$INPUT" != "y" ] && exit
 else
-	echo Upgrade of "$1" to "$2" is underway.
+	echo '	'Upgrade of $(tput bold)"$1"$(tput sgr0) to $(tput bold)"$2"$(tput sgr0) is underway.
 fi
 echo
 
@@ -52,32 +63,45 @@ set -e
 cd $STAGING
 [ ! -d "$NEWDIR" ] && tar -xf $STAGING/"$2".tar.xz
 # Sanity checks
-[ ! -f "$NEWDIR/TREE" ] && echo Warning! The TREE file for "$2" could not be found. Try running pkgmake again. Exiting now. && exit
-[ ! -f "$NEWDIR/NAME" ] && echo Warning! The NAME file for "$2" could not be found. Try running pkgmake again. Exiting now. && exit
+[ ! -f "$NEWDIR/TREE" ] && echo '	'$(tput bold)Warning!$(tput sgr0) The $(tput bold)TREE$(tput sgr0) file for $(tput bold)"$2"$(tput sgr0) could not be found. Try running pkgmake again. Exiting now. && exit
+[ ! -f "$NEWDIR/NAME" ] && echo '	'$(tput bold)Warning!$(tput sgr0) The $(tput bold)NAME$(tput sgr0) file for $(tput bold)"$2"$(tput sgr0) could not be found. Try running pkgmake again. Exiting now. && exit
 NAME="$(cat "$NEWDIR/NAME")"
 
 # The new version will overwrite the outgoing TREE and VER, but they need to be saved for comparison.
-cp -v "$PKGTREES"/"$1" "$PKGTREES/YALPACK-OUTGOING"
-cp -v "$PKGVERS"/"$1" "$PKGVERS/YALPACK-OUTGOING"
+cp "$PKGTREES"/"$1" "$PKGTREES/YALPACK-OUTGOING"
+# The backup locations contain only TREE files.
+[ -d "$VARBKUP" ] && cp "$VARBKUP"/"$1" "$VARBKUP/YALPACK-OUTGOING"
+[ -d "$ROOTBKUP" ] && cp "$ROOTBKUP"/"$1" "$ROOTBKUP/YALPACK-OUTGOING"
+cp "$PKGVERS"/"$1" "$PKGVERS/YALPACK-OUTGOING"
+
+# The new version may or may not overwrite SYMTREE and NEWFILE
+[ -f "$SYMTREES"/"$1" ] && mv "$SYMTREES"/"$1" "$SYMTREES/YALPACK-OUTGOING"
+[ -f "$SYMDESTS"/"$1" ] && mv "$SYMDESTS"/"$1" "$SYMDESTS/YALPACK-OUTGOING"
+# Just in case.
+mkdir -p "$NEWFILES"
+[ -f "$NEWFILES"/"$1" ] && cp "$NEWFILES"/"$1" "$NEWFILES/YALPACK-OUTGOING"
 
 # pkgremove, pkginst and pkgcheck can use their own error handling
 set +e
-[ "$3" = "KEEP" ] && [ "$5" = "CHOWN" ] && UPGRADE=yes /sbin/pkginst -kr "$2"
-[ "$3" = "KEEP" ] && [ "$5" != "CHOWN" ] && UPGRADE=yes /sbin/pkginst -k "$2"
-[ "$3" != "KEEP" ] && [ "$5" = "CHOWN" ] && UPGRADE=yes /sbin/pkginst -r "$2"
-[ "$3" != "KEEP" ] && [ "$5" != "CHOWN" ] && UPGRADE=yes /sbin/pkginst "$2"
+[ "$3" = "KEEP" ] && [ "$5" = "CHOWN" ] && UPGRADE=yes pkginst -kr "$2"
+[ "$3" = "KEEP" ] && [ "$5" != "CHOWN" ] && UPGRADE=yes pkginst -k "$2"
+[ "$3" != "KEEP" ] && [ "$5" = "CHOWN" ] && UPGRADE=yes pkginst -r "$2"
+[ "$3" != "KEEP" ] && [ "$5" != "CHOWN" ] && UPGRADE=yes pkginst "$2"
 # UPGRADE=yes protects the newly-installed version from interference.
-UPGRADE=yes /sbin/pkgremove -y "$1"
-CHECK=no /sbin/pkgcheck "$NAME"
+UPGRADE=yes pkgremove -y "$1"
+CHECK=no pkgcheck "$NAME"
 set -e
 
 # Checking for a new version of init
 NEWINITVER="$(/sbin/init --version | cut -d' ' -f4-)"
 
 # Reload init if new glibc or new sysvinit
-[ -n "$(grep /lib/libc.so.6 "$PKGTREES"/"$NAME")" ] || [ "$INITVER" != "$NEWINITVER" ] && /sbin/telinit U && echo init has been reloaded. && echo
+unset MESSAGE
+# Adding "or true" means the script will not crash when performing glibc or init upgrades
+[ -n "$(grep /lib/libc.so.6 "$PKGTREES"/"$NAME")" ] || [ "$INITVER" != "$NEWINITVER" ] && MESSAGE="WRITE" && telinit U || true
+[ "$MESSAGE" = "WRITE" ] && echo && echo '	'$(tput bold)init$(tput sgr0) has been reloaded, if not in chroot. && echo
 
-echo The upgrade of "$1" to "$2" is complete.
+echo '	'The upgrade of $(tput bold)"$1"$(tput sgr0) to $(tput bold)"$2"$(tput sgr0) is complete.
 echo
 }
 unset OUTGOING
@@ -89,7 +113,7 @@ for arg in "$@"; do
 	case "$arg" in
 		-h|--help)
 		echo
-		echo pkgup: Upgrade from one yalpack package to another.
+		echo $(tput bold)pkgup$(tput sgr0): Upgrade from one yalpack package to another.
 		echo
 		echo Syntax: pkgup \(options\) OLDNAME NEWNAME-NEWVER
 		echo
