Multiple updates
Updates to allow for:
* Operations without the currently-installed package tarball (pkgcheck, pkgremove, pkgup)
* "Version-less" installation of packages - for situations like multiple kernel packages (pkginst, pkgmake, pkgremove, pkgup)
* Bugfix: retained .new files no longer crash pkginst

diff --git a/src/sbin/pkginst b/src/sbin/pkginst
--- a/src/sbin/pkginst
+++ b/src/sbin/pkginst
@@ -26,9 +26,9 @@
 
 STAGING=/var/yalpack/packages
 TMP=/tmp
-PKGDIR=$STAGING/$1
+PKGDIR=$STAGING/"$1"
 PKGDATA=/var/yalpack/pkgdata
-BUILDDEST=$TMP/$1/dest
+BUILDDEST=$TMP/"$1"/dest
 PKGDEST=$PKGDIR/dest
 PKGTREES=$PKGDATA/TREES
 PKGVER=$PKGDATA/VER
@@ -59,10 +59,15 @@ do
 		j="${f%.new}"
 		# If file exists, check for differences
 		if [ -f "/$i" ]; then
-			DIFF=$(diff "$f" "/$i")
+			#DIFF="$(diff "$f" "/$i")"
+			md5f=$(md5sum "$f" | cut -d' ' -f-1)
+			md5i=$(md5sum "/$i" | cut -d' ' -f-1)
 			# If not different, new file is not needed
-			if [ -z "$DIFF" ]; then
+			if [ "$md5f" = "$md5i" ]; then
 				rm -fv "$f"
+				echo
+			else
+				echo "/$h" >> "$PKGDIR"/NEWFILES
 				echo
 			fi
 		# If file DNE, don't call the new one .new
@@ -72,11 +77,12 @@ do
 			echo
 		fi
 		# Finally, make a log with any .new files to check afterwards.	
-		[ -f "$f" ] && echo /"$i.new" >> "$PKGDIR"/NEWFILES
-		echo Done checking the .new files
-		echo
+		#[ -f "$f" ] && echo "/$h" >> "$PKGDIR"/NEWFILES
+		#echo
 	fi
 done
+echo Done copying the .new files, if any.
+echo
 
 # Copying over
 find "$PKGDEST"/ -type f,d | while read -r f;
@@ -132,6 +138,20 @@ echo Now running ldconfig...
 echo Done running ldconfig.
 echo
 
+# For the installer's edification and to update library use info
+echo
+# pkgcheck should use its own error handling instead.
+set +e
+CHECK=no pkgcheck "$NAME"
+set -e
+# Clean up afterwards
+cd "$STAGING"
+rm -rf "${PKGDIR:?}"
+echo Almost done. To retain the package tarball, enter \"y\" now.
+read -r INPUT
+echo
+[ "$INPUT" != "y" ] && rm -vf $STAGING/"$1".tar.xz && echo
+
 # Inform about any symlinks
 if [ -f "$PKGDIR"/SYMLINKS ]; then 
 	echo The following symlinks were created by the build process:
@@ -148,19 +168,8 @@ if [ -f "$PKGDIR"/NEWFILES ]; then
 	echo "$1" installed on "$(date)" >> "$PKGDATA"/NEWFILE-LOG
 	cat "$PKGDIR"/NEWFILES >> "$PKGDATA"/NEWFILE-LOG
 	echo The list has been added to "$PKGDATA"/NEWFILE-LOG for convenience.
+	echo
 fi
 
-# Should be called with UPGRADE=yes only if from within /sbin/pkgup
-if [ "${UPGRADE:-no}" != yes ]; then
-	# For the installer's edification and to update library use info
-	echo
-	# pkgcheck should use its own error handling instead.
-	set +e
-	CHECK=no pkgcheck "$1"
-	set -e
-	# Clean up afterwards
-	cd "$STAGING"
-	rm -rf "${PKGDIR:?}"
-fi
 echo Installation of "$1" complete.
 echo
diff --git a/src/sbin/pkgup b/src/sbin/pkgup
--- a/src/sbin/pkgup
+++ b/src/sbin/pkgup
@@ -25,67 +25,36 @@
 # Used to upgrade packages to a new version. HANDLE WITH CARE.
 
 STAGING=/var/yalpack/packages
-OLDDIR=$STAGING/"$1"
-OLDDEST="$OLDDIR"/dest
 NEWDIR=$STAGING/"$2"
 PKGTREES=/var/yalpack/pkgdata/TREES
 
 echo
 echo It is advised to run pkgcheck on the old package first.
 echo
-echo Upgrade from "$1" to "$2" has been requested. To proceed, press \"y\". IF YOU HAVE ANY DOUBTS, TERMINATE THE PROCESS NOW.
+echo Upgrade of "$1" to "$2" has been requested. To proceed, press \"y\". IF YOU HAVE ANY DOUBTS, TERMINATE THE PROCESS NOW.
 read -r INPUT
 echo
 [ "$INPUT" != "y" ] && exit
 
 set -e
 cd $STAGING
-
-# pkginst can use its own error handling
-set +e
-UPGRADE=yes /sbin/pkginst "$2"
-set -e
-tar -xf $STAGING/"$1".tar.xz
+[ ! -d "$NEWDIR" ] && tar -xf $STAGING/"$2".tar.xz
 # Sanity check
-[ -z "$OLDDEST" ] && echo WARNING! Old package not found. Ending process now. && exit
+[ ! -f "$NEWDIR/TREE" ] && echo Warning! The TREE file for "$2" could not be found. Try running pkgmake again. Exiting now. && exit
 
-# The user/administrator is responsible for their own home partition; upgrade will not delete anything from the home directory. Removing from the package directory here will prevent the check for later deletion.
-[ -d "$OLDDEST/home" ] && rm -rf "${OLDDEST:?}/home"
+# To save time, don't want to delete files from the old package unless they're unneeded; those shared with the new package will be overwritten in any case.
+cat "$NEWDIR"/TREE > "$PKGTREES/YALPACK-INCOMING"
+rm -r "$NEWDIR"
 
-# Checking original package for matches in other installed packages... including the newly installed upgrade. Should be safe on a package-oriented system.
-for f in $(find "$OLDDEST"/* -type f,l)
-do
-	i="${f##$OLDDEST/}"
-	# If grep -x turns up nothing, other installed packages don't need the file
-	if [ -z "$(grep -x /"$i" "$PKGTREES"/*)" ]; then
-		rm -fv /"$i"
-		# Deleting unneeded non-.new version
-		[ -f /"${i%.new}" ] && rm -fv /"${i%.new}"
-	fi
-done
-
-# Process for directories
-for d in $(find "$OLDDEST"/* -type d)
-do
-	i="${d##$OLDDEST/}"
-	if [ -d "$d" ]; then
-		x="$(ls -A /"$i")"
-		[ -z "$x" ] && rmdir -v --ignore-fail-on-non-empty /"$i"
-	fi
-done
-
-# Symlinks could theoretically get knocked out by accident. Run the install script again to be sure.
-[ -x "$NEWDIR"/install.sh ] && "$NEWDIR"/install.sh
-
-# In case of library changes
-echo Running ldconfig now...
-/sbin/ldconfig || true
-echo Done running ldconfig.
-CHECK=no pkgcheck "$2"
+# pkgremove and pkginst can use their own error handling
+set +e
+UPGRADE=yes /sbin/pkgremove "$1"
+/sbin/pkginst "$2"
+set -e
 
 # Cleaning up
 cd $STAGING
-rm -rf "$NEWDIR" "$OLDDIR"
+rm -f "$PKGTREES/YALPACK-INCOMING"
 
 echo The upgrade from "$1" to "$2" is complete.
 echo
